import { AlimentoCategoria, PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

type SeedCategory = keyof typeof AlimentoCategoria | null;

type SeedFoodRecord = {
  nombre: string;
  categoria: string;
  categoria_enum: SeedCategory;
  calorias: number;
  proteinas: number;
  carbohidratos: number;
  grasas: number;
  porcion: string;
};

const data: SeedFoodRecord[] = [
  {
    nombre: "Amaranto cocido",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 102,
    proteinas: 3.8,
    carbohidratos: 19,
    grasas: 1.6,
    porcion: "100 g",
  },
  {
    nombre: "Arepa de maíz",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 218,
    proteinas: 5,
    carbohidratos: 45,
    grasas: 1,
    porcion: "100 g",
  },
  {
    nombre: "Arroz basmati cocido",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 121,
    proteinas: 3.5,
    carbohidratos: 25,
    grasas: 0.4,
    porcion: "100 g",
  },
  {
    nombre: "Arroz blanco cocido",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 130,
    proteinas: 2.4,
    carbohidratos: 28.2,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Arroz blanco cocido blanca",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 130,
    proteinas: 2.4,
    carbohidratos: 28.2,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Arroz blanco cocido gallina",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 130,
    proteinas: 2.4,
    carbohidratos: 28.2,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Arroz integral cocido",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 123,
    proteinas: 2.7,
    carbohidratos: 25.6,
    grasas: 1,
    porcion: "100 g",
  },
  {
    nombre: "Arroz integral cocido amarilla",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 123,
    proteinas: 2.7,
    carbohidratos: 25.6,
    grasas: 1,
    porcion: "100 g",
  },
  {
    nombre: "Arroz integral cocido grande",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 123,
    proteinas: 2.7,
    carbohidratos: 25.6,
    grasas: 1,
    porcion: "100 g",
  },
  {
    nombre: "Arroz jazmín cocido",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 130,
    proteinas: 2.5,
    carbohidratos: 28,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Arroz salvaje cocido",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 101,
    proteinas: 4,
    carbohidratos: 21,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Arveja cocida",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 81,
    proteinas: 5,
    carbohidratos: 14,
    grasas: 0.4,
    porcion: "100 g",
  },
  {
    nombre: "Avena cocida",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 68,
    proteinas: 2.4,
    carbohidratos: 12,
    grasas: 1.4,
    porcion: "100 g",
  },
  {
    nombre: "Avena cocida blanca",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 68,
    proteinas: 2.4,
    carbohidratos: 12,
    grasas: 1.4,
    porcion: "100 g",
  },
  {
    nombre: "Avena cocida orgánica",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 68,
    proteinas: 2.4,
    carbohidratos: 12,
    grasas: 1.4,
    porcion: "100 g",
  },
  {
    nombre: "Avena instantánea cocida",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 70,
    proteinas: 2.5,
    carbohidratos: 12.5,
    grasas: 1.5,
    porcion: "100 g",
  },
  {
    nombre: "Avena instantánea cocida amarilla",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 70,
    proteinas: 2.5,
    carbohidratos: 12.5,
    grasas: 1.5,
    porcion: "100 g",
  },
  {
    nombre: "Avena instantánea cocida hervida",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 70,
    proteinas: 2.5,
    carbohidratos: 12.5,
    grasas: 1.5,
    porcion: "100 g",
  },
  {
    nombre: "Azúcar",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 387,
    proteinas: 0,
    carbohidratos: 100,
    grasas: 0,
    porcion: "100 g",
  },
  {
    nombre: "Bizcocho",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 330,
    proteinas: 6,
    carbohidratos: 50,
    grasas: 12,
    porcion: "100 g",
  },
  {
    nombre: "Camote amarillo cocido",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 90,
    proteinas: 1.7,
    carbohidratos: 21,
    grasas: 0.1,
    porcion: "100 g",
  },
  {
    nombre: "Camote amarillo cocido grande",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 90,
    proteinas: 1.7,
    carbohidratos: 21,
    grasas: 0.1,
    porcion: "100 g",
  },
  {
    nombre: "Camote cocido",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 86,
    proteinas: 1.6,
    carbohidratos: 20.1,
    grasas: 0.1,
    porcion: "100 g",
  },
  {
    nombre: "Camote cocido gallina",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 86,
    proteinas: 1.6,
    carbohidratos: 20.1,
    grasas: 0.1,
    porcion: "100 g",
  },
  {
    nombre: "Camote morado cocido",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 88,
    proteinas: 1.7,
    carbohidratos: 20.5,
    grasas: 0.1,
    porcion: "100 g",
  },
  {
    nombre: "Camote morado cocido pequeña",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 88,
    proteinas: 1.7,
    carbohidratos: 20.5,
    grasas: 0.1,
    porcion: "100 g",
  },
  {
    nombre: "Cebada cocida",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 123,
    proteinas: 2.3,
    carbohidratos: 28,
    grasas: 0.4,
    porcion: "100 g",
  },
  {
    nombre: "Cebada cocida",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 123,
    proteinas: 2.3,
    carbohidratos: 28,
    grasas: 0.4,
    porcion: "100 g",
  },
  {
    nombre: "Cebada cocida morada",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 123,
    proteinas: 2.3,
    carbohidratos: 28,
    grasas: 0.4,
    porcion: "100 g",
  },
  {
    nombre: "Cereal de maíz",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 370,
    proteinas: 7,
    carbohidratos: 85,
    grasas: 1,
    porcion: "100 g",
  },
  {
    nombre: "Cereal de trigo",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 360,
    proteinas: 10,
    carbohidratos: 80,
    grasas: 2,
    porcion: "100 g",
  },
  {
    nombre: "Choclo hervido",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 96,
    proteinas: 3.4,
    carbohidratos: 21,
    grasas: 1.5,
    porcion: "100 g",
  },
  {
    nombre: "Chuño rehidratado",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 105,
    proteinas: 2,
    carbohidratos: 24,
    grasas: 0.1,
    porcion: "100 g",
  },
  {
    nombre: "Croissant",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 406,
    proteinas: 8,
    carbohidratos: 45,
    grasas: 21,
    porcion: "100 g",
  },
  {
    nombre: "Cuscús cocido",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 112,
    proteinas: 3.8,
    carbohidratos: 23,
    grasas: 0.2,
    porcion: "100 g",
  },
  {
    nombre: "Donut",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 452,
    proteinas: 4.9,
    carbohidratos: 51,
    grasas: 25,
    porcion: "100 g",
  },
  {
    nombre: "Fideo cocido",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 131,
    proteinas: 5,
    carbohidratos: 25,
    grasas: 1.1,
    porcion: "100 g",
  },
  {
    nombre: "Fideo cocido de campo",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 131,
    proteinas: 5,
    carbohidratos: 25,
    grasas: 1.1,
    porcion: "100 g",
  },
  {
    nombre: "Fideo cocido sin sal",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 131,
    proteinas: 5,
    carbohidratos: 25,
    grasas: 1.1,
    porcion: "100 g",
  },
  {
    nombre: "Fideo integral cocido",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 124,
    proteinas: 5,
    carbohidratos: 27,
    grasas: 1,
    porcion: "100 g",
  },
  {
    nombre: "Frijol cocido",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 127,
    proteinas: 8.7,
    carbohidratos: 22.8,
    grasas: 0.5,
    porcion: "100 g",
  },
  {
    nombre: "Galleta integral",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 480,
    proteinas: 7,
    carbohidratos: 65,
    grasas: 20,
    porcion: "100 g",
  },
  {
    nombre: "Galleta simple",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 502,
    proteinas: 6,
    carbohidratos: 64,
    grasas: 24,
    porcion: "100 g",
  },
  {
    nombre: "Garbanzo cocido",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 164,
    proteinas: 9,
    carbohidratos: 27,
    grasas: 2.6,
    porcion: "100 g",
  },
  {
    nombre: "Gelatina preparada",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 62,
    proteinas: 1.2,
    carbohidratos: 14,
    grasas: 0,
    porcion: "100 g",
  },
  {
    nombre: "Granola",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 471,
    proteinas: 10,
    carbohidratos: 64,
    grasas: 20,
    porcion: "100 g",
  },
  {
    nombre: "Haba cocida",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 88,
    proteinas: 7.6,
    carbohidratos: 16,
    grasas: 0.4,
    porcion: "100 g",
  },
  {
    nombre: "Harina de arroz",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 366,
    proteinas: 6,
    carbohidratos: 80,
    grasas: 1,
    porcion: "100 g",
  },
  {
    nombre: "Harina de avena",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 389,
    proteinas: 17,
    carbohidratos: 66,
    grasas: 7,
    porcion: "100 g",
  },
  {
    nombre: "Harina de maíz",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 365,
    proteinas: 9,
    carbohidratos: 76,
    grasas: 4,
    porcion: "100 g",
  },
  {
    nombre: "Harina de quinua",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 368,
    proteinas: 14,
    carbohidratos: 64,
    grasas: 6,
    porcion: "100 g",
  },
  {
    nombre: "Harina de trigo",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 364,
    proteinas: 10,
    carbohidratos: 76,
    grasas: 1,
    porcion: "100 g",
  },
  {
    nombre: "Harina de yuca",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 360,
    proteinas: 1,
    carbohidratos: 88,
    grasas: 0.5,
    porcion: "100 g",
  },
  {
    nombre: "Lenteja cocida",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 116,
    proteinas: 9,
    carbohidratos: 20,
    grasas: 0.4,
    porcion: "100 g",
  },
  {
    nombre: "Maíz inflado",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 387,
    proteinas: 8,
    carbohidratos: 78,
    grasas: 4,
    porcion: "100 g",
  },
  {
    nombre: "Maíz tostado",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 450,
    proteinas: 10,
    carbohidratos: 70,
    grasas: 15,
    porcion: "100 g",
  },
  {
    nombre: "Mermelada",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 250,
    proteinas: 0.3,
    carbohidratos: 65,
    grasas: 0.2,
    porcion: "100 g",
  },
  {
    nombre: "Miel",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 304,
    proteinas: 0.3,
    carbohidratos: 82,
    grasas: 0,
    porcion: "100 g",
  },
  {
    nombre: "Mote de maíz cocido",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 120,
    proteinas: 3.2,
    carbohidratos: 26,
    grasas: 1,
    porcion: "100 g",
  },
  {
    nombre: "Mote de maíz cocido corte rodaja",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 120,
    proteinas: 3.2,
    carbohidratos: 26,
    grasas: 1,
    porcion: "100 g",
  },
  {
    nombre: "Pan blanco",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 265,
    proteinas: 9,
    carbohidratos: 49,
    grasas: 3.2,
    porcion: "100 g",
  },
  {
    nombre: "Pan de centeno",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 259,
    proteinas: 9,
    carbohidratos: 48,
    grasas: 3,
    porcion: "100 g",
  },
  {
    nombre: "Pan de molde",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 265,
    proteinas: 9,
    carbohidratos: 49,
    grasas: 3,
    porcion: "100 g",
  },
  {
    nombre: "Pan dulce",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 350,
    proteinas: 7,
    carbohidratos: 60,
    grasas: 10,
    porcion: "100 g",
  },
  {
    nombre: "Pan integral",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 247,
    proteinas: 13,
    carbohidratos: 41,
    grasas: 4.2,
    porcion: "100 g",
  },
  {
    nombre: "Pan multicereal",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 260,
    proteinas: 9,
    carbohidratos: 45,
    grasas: 6,
    porcion: "100 g",
  },
  {
    nombre: "Pan pita",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 275,
    proteinas: 9,
    carbohidratos: 55,
    grasas: 1.2,
    porcion: "100 g",
  },
  {
    nombre: "Papa amarilla cocida",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 85,
    proteinas: 2,
    carbohidratos: 19.5,
    grasas: 0.1,
    porcion: "100 g",
  },
  {
    nombre: "Papa amarilla cocida",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 85,
    proteinas: 2,
    carbohidratos: 19.5,
    grasas: 0.1,
    porcion: "100 g",
  },
  {
    nombre: "Papa blanca cocida",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 87,
    proteinas: 1.9,
    carbohidratos: 20.1,
    grasas: 0.1,
    porcion: "100 g",
  },
  {
    nombre: "Papa blanca cocida hervida",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 87,
    proteinas: 1.9,
    carbohidratos: 20.1,
    grasas: 0.1,
    porcion: "100 g",
  },
  {
    nombre: "Papa cocida",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 87,
    proteinas: 1.9,
    carbohidratos: 20.1,
    grasas: 0.1,
    porcion: "100 g",
  },
  {
    nombre: "Papa cocida orgánica",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 87,
    proteinas: 1.9,
    carbohidratos: 20.1,
    grasas: 0.1,
    porcion: "100 g",
  },
  {
    nombre: "Papa morada cocida",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 85,
    proteinas: 2,
    carbohidratos: 19,
    grasas: 0.1,
    porcion: "100 g",
  },
  {
    nombre: "Papa morada cocida sin sal",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 85,
    proteinas: 2,
    carbohidratos: 19,
    grasas: 0.1,
    porcion: "100 g",
  },
  {
    nombre: "Papa roja cocida",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 87,
    proteinas: 1.9,
    carbohidratos: 20.1,
    grasas: 0.1,
    porcion: "100 g",
  },
  {
    nombre: "Papa roja cocida al vapor",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 87,
    proteinas: 1.9,
    carbohidratos: 20.1,
    grasas: 0.1,
    porcion: "100 g",
  },
  {
    nombre: "Pasta de arroz cocida",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 130,
    proteinas: 2.4,
    carbohidratos: 28,
    grasas: 0.5,
    porcion: "100 g",
  },
  {
    nombre: "Pasta de huevo cocida",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 131,
    proteinas: 5.5,
    carbohidratos: 25,
    grasas: 1.5,
    porcion: "100 g",
  },
  {
    nombre: "Pasta integral cocida",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 124,
    proteinas: 5,
    carbohidratos: 27,
    grasas: 1,
    porcion: "100 g",
  },
  {
    nombre: "Queque",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 390,
    proteinas: 6,
    carbohidratos: 55,
    grasas: 18,
    porcion: "100 g",
  },
  {
    nombre: "Quinua cocida",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 120,
    proteinas: 4.4,
    carbohidratos: 21.3,
    grasas: 1.9,
    porcion: "100 g",
  },
  {
    nombre: "Quinua cocida morada",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 120,
    proteinas: 4.4,
    carbohidratos: 21.3,
    grasas: 1.9,
    porcion: "100 g",
  },
  {
    nombre: "Quinua cocida pequeña",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 120,
    proteinas: 4.4,
    carbohidratos: 21.3,
    grasas: 1.9,
    porcion: "100 g",
  },
  {
    nombre: "Quinua negra cocida",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 120,
    proteinas: 4.4,
    carbohidratos: 21,
    grasas: 2,
    porcion: "100 g",
  },
  {
    nombre: "Quinua negra cocida corte rodaja",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 120,
    proteinas: 4.4,
    carbohidratos: 21,
    grasas: 2,
    porcion: "100 g",
  },
  {
    nombre: "Quinua negra cocida de campo",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 120,
    proteinas: 4.4,
    carbohidratos: 21,
    grasas: 2,
    porcion: "100 g",
  },
  {
    nombre: "Quinua roja cocida",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 120,
    proteinas: 4.4,
    carbohidratos: 21,
    grasas: 2,
    porcion: "100 g",
  },
  {
    nombre: "Quinua roja cocida andina",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 120,
    proteinas: 4.4,
    carbohidratos: 21,
    grasas: 2,
    porcion: "100 g",
  },
  {
    nombre: "Quinua roja cocida corte cubo",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 120,
    proteinas: 4.4,
    carbohidratos: 21,
    grasas: 2,
    porcion: "100 g",
  },
  {
    nombre: "Rosca",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 360,
    proteinas: 7,
    carbohidratos: 58,
    grasas: 12,
    porcion: "100 g",
  },
  {
    nombre: "Sorgo cocido",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 119,
    proteinas: 3.5,
    carbohidratos: 25,
    grasas: 1,
    porcion: "100 g",
  },
  {
    nombre: "Tortilla de maíz",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 218,
    proteinas: 5.7,
    carbohidratos: 45,
    grasas: 2.8,
    porcion: "100 g",
  },
  {
    nombre: "Tortilla de trigo",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 290,
    proteinas: 8,
    carbohidratos: 48,
    grasas: 7,
    porcion: "100 g",
  },
  {
    nombre: "Trigo cocido",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 111,
    proteinas: 3.6,
    carbohidratos: 24,
    grasas: 0.4,
    porcion: "100 g",
  },
  {
    nombre: "Trigo cocido al vapor",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 111,
    proteinas: 3.6,
    carbohidratos: 24,
    grasas: 0.4,
    porcion: "100 g",
  },
  {
    nombre: "Trigo cocido andina",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 111,
    proteinas: 3.6,
    carbohidratos: 24,
    grasas: 0.4,
    porcion: "100 g",
  },
  {
    nombre: "Tunta rehidratada",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 100,
    proteinas: 1.9,
    carbohidratos: 23,
    grasas: 0.1,
    porcion: "100 g",
  },
  {
    nombre: "Yuca cocida",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 160,
    proteinas: 1.4,
    carbohidratos: 38.1,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Yuca cocida corte cubo",
    categoria: "Carbohidratos",
    categoria_enum: "Carbohidratos",
    calorias: 160,
    proteinas: 1.4,
    carbohidratos: 38.1,
    grasas: 0.3,
    porcion: "100 g",
  },
];

async function main() {
  await prisma.alimento.createMany({
    data: data.map((item) => ({
      nombre: item.nombre,
      categoria: item.categoria,
      categoria_enum: item.categoria_enum ? AlimentoCategoria[item.categoria_enum] : null,
      calorias: item.calorias,
      proteinas: item.proteinas,
      carbohidratos: item.carbohidratos,
      grasas: item.grasas,
      porcion: item.porcion,
    })),
  });

  console.log(`Insertados ${data.length} registros en 01_carbohidratos.seed.ts`);
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
