import { AlimentoCategoria, PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

type SeedCategory = keyof typeof AlimentoCategoria | null;

type SeedFoodRecord = {
  nombre: string;
  categoria: string;
  categoria_enum: SeedCategory;
  calorias: number;
  proteinas: number;
  carbohidratos: number;
  grasas: number;
  porcion: string;
};

const data: SeedFoodRecord[] = [
  {
    nombre: "Arveja cocida",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 81,
    proteinas: 5,
    carbohidratos: 14,
    grasas: 0.4,
    porcion: "100 g",
  },
  {
    nombre: "Atún en agua",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 116,
    proteinas: 26,
    carbohidratos: 0,
    grasas: 1,
    porcion: "100 g",
  },
  {
    nombre: "Atún en agua desmenuzado",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 116,
    proteinas: 26,
    carbohidratos: 0,
    grasas: 1,
    porcion: "100 g",
  },
  {
    nombre: "Atún en agua natural",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 116,
    proteinas: 26,
    carbohidratos: 0,
    grasas: 1,
    porcion: "100 g",
  },
  {
    nombre: "Atún en agua natural",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 116,
    proteinas: 26,
    carbohidratos: 0,
    grasas: 1,
    porcion: "100 g",
  },
  {
    nombre: "Atún en agua sin piel",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 116,
    proteinas: 26,
    carbohidratos: 0,
    grasas: 1,
    porcion: "100 g",
  },
  {
    nombre: "Camarón cocido",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 99,
    proteinas: 24,
    carbohidratos: 0.2,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Carne de alpaca cocida",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 140,
    proteinas: 28,
    carbohidratos: 0,
    grasas: 2.8,
    porcion: "100 g",
  },
  {
    nombre: "Carne de cerdo magra cocida",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 242,
    proteinas: 27,
    carbohidratos: 0,
    grasas: 14,
    porcion: "100 g",
  },
  {
    nombre: "Carne de cerdo magra cocida a la plancha",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 242,
    proteinas: 27,
    carbohidratos: 0,
    grasas: 14,
    porcion: "100 g",
  },
  {
    nombre: "Carne de cerdo magra cocida magra",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 242,
    proteinas: 27,
    carbohidratos: 0,
    grasas: 14,
    porcion: "100 g",
  },
  {
    nombre: "Carne de cerdo magra cocida magra",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 242,
    proteinas: 27,
    carbohidratos: 0,
    grasas: 14,
    porcion: "100 g",
  },
  {
    nombre: "Carne de cerdo magra cocida sin grasa",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 242,
    proteinas: 27,
    carbohidratos: 0,
    grasas: 14,
    porcion: "100 g",
  },
  {
    nombre: "Carne de llama cocida",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 143,
    proteinas: 28,
    carbohidratos: 0,
    grasas: 3,
    porcion: "100 g",
  },
  {
    nombre: "Carne de res magra cocida",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 217,
    proteinas: 26,
    carbohidratos: 0,
    grasas: 12,
    porcion: "100 g",
  },
  {
    nombre: "Carne de res magra cocida desmenuzado",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 217,
    proteinas: 26,
    carbohidratos: 0,
    grasas: 12,
    porcion: "100 g",
  },
  {
    nombre: "Carne de res magra cocida desmenuzado",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 217,
    proteinas: 26,
    carbohidratos: 0,
    grasas: 12,
    porcion: "100 g",
  },
  {
    nombre: "Carne de res magra cocida natural",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 217,
    proteinas: 26,
    carbohidratos: 0,
    grasas: 12,
    porcion: "100 g",
  },
  {
    nombre: "Carne de res magra cocida sin piel",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 217,
    proteinas: 26,
    carbohidratos: 0,
    grasas: 12,
    porcion: "100 g",
  },
  {
    nombre: "Carne molida magra cocida",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 250,
    proteinas: 26,
    carbohidratos: 0,
    grasas: 17,
    porcion: "100 g",
  },
  {
    nombre: "Charque desgrasado",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 250,
    proteinas: 50,
    carbohidratos: 0,
    grasas: 6,
    porcion: "100 g",
  },
  {
    nombre: "Corazón de res cocido",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 112,
    proteinas: 17,
    carbohidratos: 0,
    grasas: 4,
    porcion: "100 g",
  },
  {
    nombre: "Filete de pollo cocido",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 165,
    proteinas: 31,
    carbohidratos: 0,
    grasas: 3.6,
    porcion: "100 g",
  },
  {
    nombre: "Frijol cocido",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 127,
    proteinas: 8.7,
    carbohidratos: 22.8,
    grasas: 0.5,
    porcion: "100 g",
  },
  {
    nombre: "Garbanzo cocido",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 164,
    proteinas: 9,
    carbohidratos: 27,
    grasas: 2.6,
    porcion: "100 g",
  },
  {
    nombre: "Haba cocida",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 88,
    proteinas: 7.6,
    carbohidratos: 16,
    grasas: 0.4,
    porcion: "100 g",
  },
  {
    nombre: "Hígado de res cocido",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 175,
    proteinas: 26,
    carbohidratos: 5,
    grasas: 5,
    porcion: "100 g",
  },
  {
    nombre: "Huevo cocido",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 155,
    proteinas: 13,
    carbohidratos: 1.1,
    grasas: 11,
    porcion: "100 g",
  },
  {
    nombre: "Huevo cocido",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 155,
    proteinas: 13,
    carbohidratos: 1.1,
    grasas: 11,
    porcion: "100 g",
  },
  {
    nombre: "Huevo cocido",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 155,
    proteinas: 13,
    carbohidratos: 1.1,
    grasas: 11,
    porcion: "100 g",
  },
  {
    nombre: "Huevo cocido firme",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 155,
    proteinas: 13,
    carbohidratos: 1.1,
    grasas: 11,
    porcion: "100 g",
  },
  {
    nombre: "Huevo cocido hervido",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 155,
    proteinas: 13,
    carbohidratos: 1.1,
    grasas: 11,
    porcion: "100 g",
  },
  {
    nombre: "Huevo revuelto",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 149,
    proteinas: 10,
    carbohidratos: 1.1,
    grasas: 11,
    porcion: "100 g",
  },
  {
    nombre: "Huevo revuelto desmenuzado",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 149,
    proteinas: 10,
    carbohidratos: 1.1,
    grasas: 11,
    porcion: "100 g",
  },
  {
    nombre: "Huevo revuelto natural",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 149,
    proteinas: 10,
    carbohidratos: 1.1,
    grasas: 11,
    porcion: "100 g",
  },
  {
    nombre: "Huevo revuelto sin piel",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 149,
    proteinas: 10,
    carbohidratos: 1.1,
    grasas: 11,
    porcion: "100 g",
  },
  {
    nombre: "Huevo revuelto sin piel",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 149,
    proteinas: 10,
    carbohidratos: 1.1,
    grasas: 11,
    porcion: "100 g",
  },
  {
    nombre: "Jurel cocido",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 205,
    proteinas: 19,
    carbohidratos: 0,
    grasas: 13,
    porcion: "100 g",
  },
  {
    nombre: "Jurel cocido desmenuzado",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 205,
    proteinas: 19,
    carbohidratos: 0,
    grasas: 13,
    porcion: "100 g",
  },
  {
    nombre: "Jurel cocido natural",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 205,
    proteinas: 19,
    carbohidratos: 0,
    grasas: 13,
    porcion: "100 g",
  },
  {
    nombre: "Jurel cocido sin piel",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 205,
    proteinas: 19,
    carbohidratos: 0,
    grasas: 13,
    porcion: "100 g",
  },
  {
    nombre: "Kéfir",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 41,
    proteinas: 3.5,
    carbohidratos: 4,
    grasas: 1,
    porcion: "100 g",
  },
  {
    nombre: "Leche descremada",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 34,
    proteinas: 3.4,
    carbohidratos: 5,
    grasas: 0.1,
    porcion: "100 g",
  },
  {
    nombre: "Leche descremada desmenuzado",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 34,
    proteinas: 3.4,
    carbohidratos: 5,
    grasas: 0.1,
    porcion: "100 g",
  },
  {
    nombre: "Leche descremada natural",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 34,
    proteinas: 3.4,
    carbohidratos: 5,
    grasas: 0.1,
    porcion: "100 g",
  },
  {
    nombre: "Leche descremada natural",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 34,
    proteinas: 3.4,
    carbohidratos: 5,
    grasas: 0.1,
    porcion: "100 g",
  },
  {
    nombre: "Leche descremada sin piel",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 34,
    proteinas: 3.4,
    carbohidratos: 5,
    grasas: 0.1,
    porcion: "100 g",
  },
  {
    nombre: "Leche entera",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 61,
    proteinas: 3.2,
    carbohidratos: 4.8,
    grasas: 3.3,
    porcion: "100 g",
  },
  {
    nombre: "Leche entera a la plancha",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 61,
    proteinas: 3.2,
    carbohidratos: 4.8,
    grasas: 3.3,
    porcion: "100 g",
  },
  {
    nombre: "Leche entera magra",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 61,
    proteinas: 3.2,
    carbohidratos: 4.8,
    grasas: 3.3,
    porcion: "100 g",
  },
  {
    nombre: "Leche entera sin grasa",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 61,
    proteinas: 3.2,
    carbohidratos: 4.8,
    grasas: 3.3,
    porcion: "100 g",
  },
  {
    nombre: "Leche entera sin grasa",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 61,
    proteinas: 3.2,
    carbohidratos: 4.8,
    grasas: 3.3,
    porcion: "100 g",
  },
  {
    nombre: "Lenteja cocida",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 116,
    proteinas: 9,
    carbohidratos: 20,
    grasas: 0.4,
    porcion: "100 g",
  },
  {
    nombre: "Molleja de pollo cocida",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 154,
    proteinas: 30,
    carbohidratos: 0,
    grasas: 3,
    porcion: "100 g",
  },
  {
    nombre: "Muslo de pollo cocido",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 177,
    proteinas: 24,
    carbohidratos: 0,
    grasas: 8,
    porcion: "100 g",
  },
  {
    nombre: "Muslo de pollo cocido",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 177,
    proteinas: 24,
    carbohidratos: 0,
    grasas: 8,
    porcion: "100 g",
  },
  {
    nombre: "Muslo de pollo cocido firme",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 177,
    proteinas: 24,
    carbohidratos: 0,
    grasas: 8,
    porcion: "100 g",
  },
  {
    nombre: "Muslo de pollo cocido hervido",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 177,
    proteinas: 24,
    carbohidratos: 0,
    grasas: 8,
    porcion: "100 g",
  },
  {
    nombre: "Muslo de pollo cocido hervido",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 177,
    proteinas: 24,
    carbohidratos: 0,
    grasas: 8,
    porcion: "100 g",
  },
  {
    nombre: "Pavo cocido",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 135,
    proteinas: 29,
    carbohidratos: 0,
    grasas: 1.6,
    porcion: "100 g",
  },
  {
    nombre: "Pechuga de pollo cocida",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 165,
    proteinas: 31,
    carbohidratos: 0,
    grasas: 3.6,
    porcion: "100 g",
  },
  {
    nombre: "Pechuga de pollo cocida a la plancha",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 165,
    proteinas: 31,
    carbohidratos: 0,
    grasas: 3.6,
    porcion: "100 g",
  },
  {
    nombre: "Pechuga de pollo cocida a la plancha",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 165,
    proteinas: 31,
    carbohidratos: 0,
    grasas: 3.6,
    porcion: "100 g",
  },
  {
    nombre: "Pechuga de pollo cocida magra",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 165,
    proteinas: 31,
    carbohidratos: 0,
    grasas: 3.6,
    porcion: "100 g",
  },
  {
    nombre: "Pechuga de pollo cocida sin grasa",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 165,
    proteinas: 31,
    carbohidratos: 0,
    grasas: 3.6,
    porcion: "100 g",
  },
  {
    nombre: "Pescado blanco cocido",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 128,
    proteinas: 26,
    carbohidratos: 0,
    grasas: 2.7,
    porcion: "100 g",
  },
  {
    nombre: "Pescado blanco cocido",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 128,
    proteinas: 26,
    carbohidratos: 0,
    grasas: 2.7,
    porcion: "100 g",
  },
  {
    nombre: "Pescado blanco cocido firme",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 128,
    proteinas: 26,
    carbohidratos: 0,
    grasas: 2.7,
    porcion: "100 g",
  },
  {
    nombre: "Pescado blanco cocido firme",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 128,
    proteinas: 26,
    carbohidratos: 0,
    grasas: 2.7,
    porcion: "100 g",
  },
  {
    nombre: "Pescado blanco cocido hervido",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 128,
    proteinas: 26,
    carbohidratos: 0,
    grasas: 2.7,
    porcion: "100 g",
  },
  {
    nombre: "Pescado de río cocido",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 130,
    proteinas: 25,
    carbohidratos: 0,
    grasas: 3,
    porcion: "100 g",
  },
  {
    nombre: "Pierna de pollo cocida",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 180,
    proteinas: 24,
    carbohidratos: 0,
    grasas: 9,
    porcion: "100 g",
  },
  {
    nombre: "Pollo desmenuzado cocido",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 165,
    proteinas: 31,
    carbohidratos: 0,
    grasas: 3.6,
    porcion: "100 g",
  },
  {
    nombre: "Quesillo",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 250,
    proteinas: 17,
    carbohidratos: 3,
    grasas: 20,
    porcion: "100 g",
  },
  {
    nombre: "Queso fresco",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 265,
    proteinas: 18,
    carbohidratos: 3,
    grasas: 21,
    porcion: "100 g",
  },
  {
    nombre: "Queso fresco a la plancha",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 265,
    proteinas: 18,
    carbohidratos: 3,
    grasas: 21,
    porcion: "100 g",
  },
  {
    nombre: "Queso fresco magra",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 265,
    proteinas: 18,
    carbohidratos: 3,
    grasas: 21,
    porcion: "100 g",
  },
  {
    nombre: "Queso fresco sin grasa",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 265,
    proteinas: 18,
    carbohidratos: 3,
    grasas: 21,
    porcion: "100 g",
  },
  {
    nombre: "Requesón",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 98,
    proteinas: 11,
    carbohidratos: 3.4,
    grasas: 4.3,
    porcion: "100 g",
  },
  {
    nombre: "Riñón de res cocido",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 99,
    proteinas: 17,
    carbohidratos: 0,
    grasas: 3,
    porcion: "100 g",
  },
  {
    nombre: "Sardina",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 208,
    proteinas: 25,
    carbohidratos: 0,
    grasas: 11,
    porcion: "100 g",
  },
  {
    nombre: "Sardina a la plancha",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 208,
    proteinas: 25,
    carbohidratos: 0,
    grasas: 11,
    porcion: "100 g",
  },
  {
    nombre: "Sardina magra",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 208,
    proteinas: 25,
    carbohidratos: 0,
    grasas: 11,
    porcion: "100 g",
  },
  {
    nombre: "Sardina sin grasa",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 208,
    proteinas: 25,
    carbohidratos: 0,
    grasas: 11,
    porcion: "100 g",
  },
  {
    nombre: "Sardina sin grasa",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 208,
    proteinas: 25,
    carbohidratos: 0,
    grasas: 11,
    porcion: "100 g",
  },
  {
    nombre: "Soya cocida",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 173,
    proteinas: 16,
    carbohidratos: 9.9,
    grasas: 9,
    porcion: "100 g",
  },
  {
    nombre: "Surubí cocido",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 140,
    proteinas: 24,
    carbohidratos: 0,
    grasas: 4,
    porcion: "100 g",
  },
  {
    nombre: "Tempeh",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 193,
    proteinas: 20,
    carbohidratos: 9.4,
    grasas: 11,
    porcion: "100 g",
  },
  {
    nombre: "Tofu firme",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 144,
    proteinas: 15,
    carbohidratos: 3.9,
    grasas: 8.7,
    porcion: "100 g",
  },
  {
    nombre: "Trucha cocida",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 148,
    proteinas: 20,
    carbohidratos: 0,
    grasas: 7,
    porcion: "100 g",
  },
  {
    nombre: "Trucha cocida cocido",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 148,
    proteinas: 20,
    carbohidratos: 0,
    grasas: 7,
    porcion: "100 g",
  },
  {
    nombre: "Trucha cocida cocido",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 148,
    proteinas: 20,
    carbohidratos: 0,
    grasas: 7,
    porcion: "100 g",
  },
  {
    nombre: "Trucha cocida firme",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 148,
    proteinas: 20,
    carbohidratos: 0,
    grasas: 7,
    porcion: "100 g",
  },
  {
    nombre: "Trucha cocida hervido",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 148,
    proteinas: 20,
    carbohidratos: 0,
    grasas: 7,
    porcion: "100 g",
  },
  {
    nombre: "Yogur griego natural",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 97,
    proteinas: 9,
    carbohidratos: 3.6,
    grasas: 5,
    porcion: "100 g",
  },
  {
    nombre: "Yogur griego natural cocido",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 97,
    proteinas: 9,
    carbohidratos: 3.6,
    grasas: 5,
    porcion: "100 g",
  },
  {
    nombre: "Yogur griego natural firme",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 97,
    proteinas: 9,
    carbohidratos: 3.6,
    grasas: 5,
    porcion: "100 g",
  },
  {
    nombre: "Yogur griego natural firme",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 97,
    proteinas: 9,
    carbohidratos: 3.6,
    grasas: 5,
    porcion: "100 g",
  },
  {
    nombre: "Yogur griego natural hervido",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 97,
    proteinas: 9,
    carbohidratos: 3.6,
    grasas: 5,
    porcion: "100 g",
  },
  {
    nombre: "Yogur natural",
    categoria: "Proteinas",
    categoria_enum: "Proteinas",
    calorias: 61,
    proteinas: 3.5,
    carbohidratos: 4.7,
    grasas: 3.3,
    porcion: "100 g",
  },
];

async function main() {
  await prisma.alimento.createMany({
    data: data.map((item) => ({
      nombre: item.nombre,
      categoria: item.categoria,
      categoria_enum: item.categoria_enum ? AlimentoCategoria[item.categoria_enum] : null,
      calorias: item.calorias,
      proteinas: item.proteinas,
      carbohidratos: item.carbohidratos,
      grasas: item.grasas,
      porcion: item.porcion,
    })),
  });

  console.log(`Insertados ${data.length} registros en 02_proteinas.seed.ts`);
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
