import { AlimentoCategoria, PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

type SeedCategory = keyof typeof AlimentoCategoria | null;

type SeedFoodRecord = {
  nombre: string;
  categoria: string;
  categoria_enum: SeedCategory;
  calorias: number;
  proteinas: number;
  carbohidratos: number;
  grasas: number;
  porcion: string;
};

const data: SeedFoodRecord[] = [
  {
    nombre: "Aceite de girasol",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 884,
    proteinas: 0,
    carbohidratos: 0,
    grasas: 100,
    porcion: "100 g",
  },
  {
    nombre: "Aceite de girasol orgánico",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 884,
    proteinas: 0,
    carbohidratos: 0,
    grasas: 100,
    porcion: "100 g",
  },
  {
    nombre: "Aceite de girasol salado",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 884,
    proteinas: 0,
    carbohidratos: 0,
    grasas: 100,
    porcion: "100 g",
  },
  {
    nombre: "Aceite de girasol tostado",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 884,
    proteinas: 0,
    carbohidratos: 0,
    grasas: 100,
    porcion: "100 g",
  },
  {
    nombre: "Aceite de maíz",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 884,
    proteinas: 0,
    carbohidratos: 0,
    grasas: 100,
    porcion: "100 g",
  },
  {
    nombre: "Aceite de maíz orgánico",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 884,
    proteinas: 0,
    carbohidratos: 0,
    grasas: 100,
    porcion: "100 g",
  },
  {
    nombre: "Aceite de maíz salado",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 884,
    proteinas: 0,
    carbohidratos: 0,
    grasas: 100,
    porcion: "100 g",
  },
  {
    nombre: "Aceite de maíz tostado",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 884,
    proteinas: 0,
    carbohidratos: 0,
    grasas: 100,
    porcion: "100 g",
  },
  {
    nombre: "Aceite de oliva",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 884,
    proteinas: 0,
    carbohidratos: 0,
    grasas: 100,
    porcion: "100 g",
  },
  {
    nombre: "Aceite de oliva",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 884,
    proteinas: 0,
    carbohidratos: 0,
    grasas: 100,
    porcion: "100 g",
  },
  {
    nombre: "Aceite de oliva crudo",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 884,
    proteinas: 0,
    carbohidratos: 0,
    grasas: 100,
    porcion: "100 g",
  },
  {
    nombre: "Aceite de oliva sin sal",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 884,
    proteinas: 0,
    carbohidratos: 0,
    grasas: 100,
    porcion: "100 g",
  },
  {
    nombre: "Aceite de soya",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 884,
    proteinas: 0,
    carbohidratos: 0,
    grasas: 100,
    porcion: "100 g",
  },
  {
    nombre: "Aceite de soya crudo",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 884,
    proteinas: 0,
    carbohidratos: 0,
    grasas: 100,
    porcion: "100 g",
  },
  {
    nombre: "Aceite de soya natural",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 884,
    proteinas: 0,
    carbohidratos: 0,
    grasas: 100,
    porcion: "100 g",
  },
  {
    nombre: "Aceite de soya sin sal",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 884,
    proteinas: 0,
    carbohidratos: 0,
    grasas: 100,
    porcion: "100 g",
  },
  {
    nombre: "Aceituna",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 115,
    proteinas: 0.8,
    carbohidratos: 6,
    grasas: 10.7,
    porcion: "100 g",
  },
  {
    nombre: "Aceituna negra",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 115,
    proteinas: 0.8,
    carbohidratos: 6,
    grasas: 10.7,
    porcion: "100 g",
  },
  {
    nombre: "Aceituna verde",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 145,
    proteinas: 1,
    carbohidratos: 4,
    grasas: 15,
    porcion: "100 g",
  },
  {
    nombre: "Aguacate",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 160,
    proteinas: 2,
    carbohidratos: 8.5,
    grasas: 14.7,
    porcion: "100 g",
  },
  {
    nombre: "Aguacate orgánico",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 160,
    proteinas: 2,
    carbohidratos: 8.5,
    grasas: 14.7,
    porcion: "100 g",
  },
  {
    nombre: "Aguacate salado",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 160,
    proteinas: 2,
    carbohidratos: 8.5,
    grasas: 14.7,
    porcion: "100 g",
  },
  {
    nombre: "Aguacate tostado",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 160,
    proteinas: 2,
    carbohidratos: 8.5,
    grasas: 14.7,
    porcion: "100 g",
  },
  {
    nombre: "Almendra",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 579,
    proteinas: 21,
    carbohidratos: 22,
    grasas: 50,
    porcion: "100 g",
  },
  {
    nombre: "Almendra orgánico",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 579,
    proteinas: 21,
    carbohidratos: 22,
    grasas: 50,
    porcion: "100 g",
  },
  {
    nombre: "Almendra salado",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 579,
    proteinas: 21,
    carbohidratos: 22,
    grasas: 50,
    porcion: "100 g",
  },
  {
    nombre: "Almendra tostado",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 579,
    proteinas: 21,
    carbohidratos: 22,
    grasas: 50,
    porcion: "100 g",
  },
  {
    nombre: "Avellana",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 628,
    proteinas: 15,
    carbohidratos: 17,
    grasas: 61,
    porcion: "100 g",
  },
  {
    nombre: "Avellana orgánico",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 628,
    proteinas: 15,
    carbohidratos: 17,
    grasas: 61,
    porcion: "100 g",
  },
  {
    nombre: "Avellana salado",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 628,
    proteinas: 15,
    carbohidratos: 17,
    grasas: 61,
    porcion: "100 g",
  },
  {
    nombre: "Avellana tostado",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 628,
    proteinas: 15,
    carbohidratos: 17,
    grasas: 61,
    porcion: "100 g",
  },
  {
    nombre: "Castaña",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 656,
    proteinas: 14,
    carbohidratos: 12,
    grasas: 67,
    porcion: "100 g",
  },
  {
    nombre: "Castaña crudo",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 656,
    proteinas: 14,
    carbohidratos: 12,
    grasas: 67,
    porcion: "100 g",
  },
  {
    nombre: "Castaña natural",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 656,
    proteinas: 14,
    carbohidratos: 12,
    grasas: 67,
    porcion: "100 g",
  },
  {
    nombre: "Castaña sin sal",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 656,
    proteinas: 14,
    carbohidratos: 12,
    grasas: 67,
    porcion: "100 g",
  },
  {
    nombre: "Coco rallado",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 660,
    proteinas: 7,
    carbohidratos: 24,
    grasas: 64,
    porcion: "100 g",
  },
  {
    nombre: "Coco rallado crudo",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 660,
    proteinas: 7,
    carbohidratos: 24,
    grasas: 64,
    porcion: "100 g",
  },
  {
    nombre: "Coco rallado natural",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 660,
    proteinas: 7,
    carbohidratos: 24,
    grasas: 64,
    porcion: "100 g",
  },
  {
    nombre: "Coco rallado sin sal",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 660,
    proteinas: 7,
    carbohidratos: 24,
    grasas: 64,
    porcion: "100 g",
  },
  {
    nombre: "Crema de almendra",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 614,
    proteinas: 21,
    carbohidratos: 19,
    grasas: 56,
    porcion: "100 g",
  },
  {
    nombre: "Crema de leche",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 340,
    proteinas: 2,
    carbohidratos: 3,
    grasas: 36,
    porcion: "100 g",
  },
  {
    nombre: "Crema de maní",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 588,
    proteinas: 25,
    carbohidratos: 20,
    grasas: 50,
    porcion: "100 g",
  },
  {
    nombre: "Grasa de res",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 902,
    proteinas: 0,
    carbohidratos: 0,
    grasas: 100,
    porcion: "100 g",
  },
  {
    nombre: "Huevo entero",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 155,
    proteinas: 13,
    carbohidratos: 1.1,
    grasas: 11,
    porcion: "100 g",
  },
  {
    nombre: "Leche de coco",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 230,
    proteinas: 2.3,
    carbohidratos: 6,
    grasas: 24,
    porcion: "100 g",
  },
  {
    nombre: "Leche de coco orgánico",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 230,
    proteinas: 2.3,
    carbohidratos: 6,
    grasas: 24,
    porcion: "100 g",
  },
  {
    nombre: "Leche de coco salado",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 230,
    proteinas: 2.3,
    carbohidratos: 6,
    grasas: 24,
    porcion: "100 g",
  },
  {
    nombre: "Leche de coco tostado",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 230,
    proteinas: 2.3,
    carbohidratos: 6,
    grasas: 24,
    porcion: "100 g",
  },
  {
    nombre: "Linaza",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 534,
    proteinas: 18,
    carbohidratos: 29,
    grasas: 42,
    porcion: "100 g",
  },
  {
    nombre: "Linaza crudo",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 534,
    proteinas: 18,
    carbohidratos: 29,
    grasas: 42,
    porcion: "100 g",
  },
  {
    nombre: "Linaza natural",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 534,
    proteinas: 18,
    carbohidratos: 29,
    grasas: 42,
    porcion: "100 g",
  },
  {
    nombre: "Linaza sin sal",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 534,
    proteinas: 18,
    carbohidratos: 29,
    grasas: 42,
    porcion: "100 g",
  },
  {
    nombre: "Macadamia",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 718,
    proteinas: 8,
    carbohidratos: 14,
    grasas: 76,
    porcion: "100 g",
  },
  {
    nombre: "Maní",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 567,
    proteinas: 26,
    carbohidratos: 16,
    grasas: 49,
    porcion: "100 g",
  },
  {
    nombre: "Maní crudo",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 567,
    proteinas: 26,
    carbohidratos: 16,
    grasas: 49,
    porcion: "100 g",
  },
  {
    nombre: "Maní natural",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 567,
    proteinas: 26,
    carbohidratos: 16,
    grasas: 49,
    porcion: "100 g",
  },
  {
    nombre: "Maní sin sal",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 567,
    proteinas: 26,
    carbohidratos: 16,
    grasas: 49,
    porcion: "100 g",
  },
  {
    nombre: "Manteca de cerdo",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 902,
    proteinas: 0,
    carbohidratos: 0,
    grasas: 100,
    porcion: "100 g",
  },
  {
    nombre: "Mantequilla",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 717,
    proteinas: 0.9,
    carbohidratos: 0.1,
    grasas: 81,
    porcion: "100 g",
  },
  {
    nombre: "Mantequilla crudo",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 717,
    proteinas: 0.9,
    carbohidratos: 0.1,
    grasas: 81,
    porcion: "100 g",
  },
  {
    nombre: "Mantequilla natural",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 717,
    proteinas: 0.9,
    carbohidratos: 0.1,
    grasas: 81,
    porcion: "100 g",
  },
  {
    nombre: "Mantequilla sin sal",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 717,
    proteinas: 0.9,
    carbohidratos: 0.1,
    grasas: 81,
    porcion: "100 g",
  },
  {
    nombre: "Margarina",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 717,
    proteinas: 0.2,
    carbohidratos: 0.7,
    grasas: 80,
    porcion: "100 g",
  },
  {
    nombre: "Margarina orgánico",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 717,
    proteinas: 0.2,
    carbohidratos: 0.7,
    grasas: 80,
    porcion: "100 g",
  },
  {
    nombre: "Margarina salado",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 717,
    proteinas: 0.2,
    carbohidratos: 0.7,
    grasas: 80,
    porcion: "100 g",
  },
  {
    nombre: "Margarina tostado",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 717,
    proteinas: 0.2,
    carbohidratos: 0.7,
    grasas: 80,
    porcion: "100 g",
  },
  {
    nombre: "Mayonesa",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 680,
    proteinas: 1,
    carbohidratos: 1,
    grasas: 75,
    porcion: "100 g",
  },
  {
    nombre: "Nuez",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 654,
    proteinas: 15,
    carbohidratos: 14,
    grasas: 65,
    porcion: "100 g",
  },
  {
    nombre: "Nuez crudo",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 654,
    proteinas: 15,
    carbohidratos: 14,
    grasas: 65,
    porcion: "100 g",
  },
  {
    nombre: "Nuez de Brasil",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 659,
    proteinas: 14,
    carbohidratos: 12,
    grasas: 67,
    porcion: "100 g",
  },
  {
    nombre: "Nuez natural",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 654,
    proteinas: 15,
    carbohidratos: 14,
    grasas: 65,
    porcion: "100 g",
  },
  {
    nombre: "Nuez sin sal",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 654,
    proteinas: 15,
    carbohidratos: 14,
    grasas: 65,
    porcion: "100 g",
  },
  {
    nombre: "Palta",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 160,
    proteinas: 2,
    carbohidratos: 8.5,
    grasas: 14.7,
    porcion: "100 g",
  },
  {
    nombre: "Palta crudo",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 160,
    proteinas: 2,
    carbohidratos: 8.5,
    grasas: 14.7,
    porcion: "100 g",
  },
  {
    nombre: "Palta natural",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 160,
    proteinas: 2,
    carbohidratos: 8.5,
    grasas: 14.7,
    porcion: "100 g",
  },
  {
    nombre: "Palta sin sal",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 160,
    proteinas: 2,
    carbohidratos: 8.5,
    grasas: 14.7,
    porcion: "100 g",
  },
  {
    nombre: "Pecanas",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 691,
    proteinas: 9,
    carbohidratos: 14,
    grasas: 72,
    porcion: "100 g",
  },
  {
    nombre: "Pepitas de zapallo",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 559,
    proteinas: 30,
    carbohidratos: 11,
    grasas: 49,
    porcion: "100 g",
  },
  {
    nombre: "Pepitas de zapallo orgánico",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 559,
    proteinas: 30,
    carbohidratos: 11,
    grasas: 49,
    porcion: "100 g",
  },
  {
    nombre: "Pepitas de zapallo salado",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 559,
    proteinas: 30,
    carbohidratos: 11,
    grasas: 49,
    porcion: "100 g",
  },
  {
    nombre: "Pepitas de zapallo tostado",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 559,
    proteinas: 30,
    carbohidratos: 11,
    grasas: 49,
    porcion: "100 g",
  },
  {
    nombre: "Pistachos",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 562,
    proteinas: 20,
    carbohidratos: 28,
    grasas: 45,
    porcion: "100 g",
  },
  {
    nombre: "Queso crema",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 342,
    proteinas: 6,
    carbohidratos: 4,
    grasas: 34,
    porcion: "100 g",
  },
  {
    nombre: "Queso mantecoso",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 350,
    proteinas: 24,
    carbohidratos: 2,
    grasas: 28,
    porcion: "100 g",
  },
  {
    nombre: "Semilla de amapola",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 525,
    proteinas: 18,
    carbohidratos: 28,
    grasas: 42,
    porcion: "100 g",
  },
  {
    nombre: "Semilla de calabaza",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 559,
    proteinas: 30,
    carbohidratos: 11,
    grasas: 49,
    porcion: "100 g",
  },
  {
    nombre: "Semilla de chía",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 486,
    proteinas: 17,
    carbohidratos: 42,
    grasas: 31,
    porcion: "100 g",
  },
  {
    nombre: "Semilla de chía orgánico",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 486,
    proteinas: 17,
    carbohidratos: 42,
    grasas: 31,
    porcion: "100 g",
  },
  {
    nombre: "Semilla de chía salado",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 486,
    proteinas: 17,
    carbohidratos: 42,
    grasas: 31,
    porcion: "100 g",
  },
  {
    nombre: "Semilla de chía tostado",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 486,
    proteinas: 17,
    carbohidratos: 42,
    grasas: 31,
    porcion: "100 g",
  },
  {
    nombre: "Semilla de girasol",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 584,
    proteinas: 21,
    carbohidratos: 20,
    grasas: 51,
    porcion: "100 g",
  },
  {
    nombre: "Semilla de girasol crudo",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 584,
    proteinas: 21,
    carbohidratos: 20,
    grasas: 51,
    porcion: "100 g",
  },
  {
    nombre: "Semilla de girasol natural",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 584,
    proteinas: 21,
    carbohidratos: 20,
    grasas: 51,
    porcion: "100 g",
  },
  {
    nombre: "Semilla de girasol sin sal",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 584,
    proteinas: 21,
    carbohidratos: 20,
    grasas: 51,
    porcion: "100 g",
  },
  {
    nombre: "Sésamo",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 573,
    proteinas: 18,
    carbohidratos: 23,
    grasas: 50,
    porcion: "100 g",
  },
  {
    nombre: "Sésamo orgánico",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 573,
    proteinas: 18,
    carbohidratos: 23,
    grasas: 50,
    porcion: "100 g",
  },
  {
    nombre: "Sésamo salado",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 573,
    proteinas: 18,
    carbohidratos: 23,
    grasas: 50,
    porcion: "100 g",
  },
  {
    nombre: "Sésamo tostado",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 573,
    proteinas: 18,
    carbohidratos: 23,
    grasas: 50,
    porcion: "100 g",
  },
  {
    nombre: "Tahini",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 595,
    proteinas: 17,
    carbohidratos: 21,
    grasas: 53,
    porcion: "100 g",
  },
  {
    nombre: "Yema de huevo",
    categoria: "Grasos",
    categoria_enum: "Grasos",
    calorias: 322,
    proteinas: 16,
    carbohidratos: 3.6,
    grasas: 27,
    porcion: "100 g",
  },
];

async function main() {
  await prisma.alimento.createMany({
    data: data.map((item) => ({
      nombre: item.nombre,
      categoria: item.categoria,
      categoria_enum: item.categoria_enum ? AlimentoCategoria[item.categoria_enum] : null,
      calorias: item.calorias,
      proteinas: item.proteinas,
      carbohidratos: item.carbohidratos,
      grasas: item.grasas,
      porcion: item.porcion,
    })),
  });

  console.log(`Insertados ${data.length} registros en 03_grasas.seed.ts`);
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
