import { AlimentoCategoria, PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

type SeedCategory = keyof typeof AlimentoCategoria | null;

type SeedFoodRecord = {
  nombre: string;
  categoria: string;
  categoria_enum: SeedCategory;
  calorias: number;
  proteinas: number;
  carbohidratos: number;
  grasas: number;
  porcion: string;
};

const data: SeedFoodRecord[] = [
  {
    nombre: "Acerola",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 32,
    proteinas: 0.4,
    carbohidratos: 8,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Arándano",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 57,
    proteinas: 0.7,
    carbohidratos: 14,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Arándano fresco",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 57,
    proteinas: 0.7,
    carbohidratos: 14,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Arándano sin cáscara",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 57,
    proteinas: 0.7,
    carbohidratos: 14,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Arándano verde",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 57,
    proteinas: 0.7,
    carbohidratos: 14,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Banana",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 89,
    proteinas: 1.1,
    carbohidratos: 23,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Banana andino",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 89,
    proteinas: 1.1,
    carbohidratos: 23,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Banana cortado",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 89,
    proteinas: 1.1,
    carbohidratos: 23,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Banana maduro",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 89,
    proteinas: 1.1,
    carbohidratos: 23,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Cereza",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 63,
    proteinas: 1.1,
    carbohidratos: 16,
    grasas: 0.2,
    porcion: "100 g",
  },
  {
    nombre: "Cereza andino",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 63,
    proteinas: 1.1,
    carbohidratos: 16,
    grasas: 0.2,
    porcion: "100 g",
  },
  {
    nombre: "Cereza cortado",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 63,
    proteinas: 1.1,
    carbohidratos: 16,
    grasas: 0.2,
    porcion: "100 g",
  },
  {
    nombre: "Cereza maduro",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 63,
    proteinas: 1.1,
    carbohidratos: 16,
    grasas: 0.2,
    porcion: "100 g",
  },
  {
    nombre: "Chirimoya",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 75,
    proteinas: 1.6,
    carbohidratos: 18,
    grasas: 0.7,
    porcion: "100 g",
  },
  {
    nombre: "Ciruela",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 46,
    proteinas: 0.7,
    carbohidratos: 11,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Ciruela fresco",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 46,
    proteinas: 0.7,
    carbohidratos: 11,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Ciruela sin cáscara",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 46,
    proteinas: 0.7,
    carbohidratos: 11,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Ciruela verde",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 46,
    proteinas: 0.7,
    carbohidratos: 11,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Coco fresco",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 354,
    proteinas: 3.3,
    carbohidratos: 15.2,
    grasas: 33.5,
    porcion: "100 g",
  },
  {
    nombre: "Dátil",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 282,
    proteinas: 2.5,
    carbohidratos: 75,
    grasas: 0.4,
    porcion: "100 g",
  },
  {
    nombre: "Durazno",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 39,
    proteinas: 0.9,
    carbohidratos: 10,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Durazno andino",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 39,
    proteinas: 0.9,
    carbohidratos: 10,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Durazno cortado",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 39,
    proteinas: 0.9,
    carbohidratos: 10,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Durazno maduro",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 39,
    proteinas: 0.9,
    carbohidratos: 10,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Frambuesa",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 52,
    proteinas: 1.2,
    carbohidratos: 12,
    grasas: 0.7,
    porcion: "100 g",
  },
  {
    nombre: "Frambuesa andino",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 52,
    proteinas: 1.2,
    carbohidratos: 12,
    grasas: 0.7,
    porcion: "100 g",
  },
  {
    nombre: "Frambuesa cortado",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 52,
    proteinas: 1.2,
    carbohidratos: 12,
    grasas: 0.7,
    porcion: "100 g",
  },
  {
    nombre: "Frambuesa maduro",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 52,
    proteinas: 1.2,
    carbohidratos: 12,
    grasas: 0.7,
    porcion: "100 g",
  },
  {
    nombre: "Fresa",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 32,
    proteinas: 0.7,
    carbohidratos: 8,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Fresa andino",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 32,
    proteinas: 0.7,
    carbohidratos: 8,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Fresa cortado",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 32,
    proteinas: 0.7,
    carbohidratos: 8,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Fresa maduro",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 32,
    proteinas: 0.7,
    carbohidratos: 8,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Frutilla",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 32,
    proteinas: 0.7,
    carbohidratos: 8,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Frutilla fresco",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 32,
    proteinas: 0.7,
    carbohidratos: 8,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Frutilla sin cáscara",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 32,
    proteinas: 0.7,
    carbohidratos: 8,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Frutilla verde",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 32,
    proteinas: 0.7,
    carbohidratos: 8,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Granada",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 83,
    proteinas: 1.7,
    carbohidratos: 19,
    grasas: 1.2,
    porcion: "100 g",
  },
  {
    nombre: "Guayaba",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 68,
    proteinas: 2.6,
    carbohidratos: 14,
    grasas: 1,
    porcion: "100 g",
  },
  {
    nombre: "Guinda",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 50,
    proteinas: 1,
    carbohidratos: 12,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Higo",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 74,
    proteinas: 0.8,
    carbohidratos: 19,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Higo seco",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 249,
    proteinas: 3.3,
    carbohidratos: 64,
    grasas: 0.9,
    porcion: "100 g",
  },
  {
    nombre: "Kiwi",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 61,
    proteinas: 1.1,
    carbohidratos: 15,
    grasas: 0.5,
    porcion: "100 g",
  },
  {
    nombre: "Kiwi fresco",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 61,
    proteinas: 1.1,
    carbohidratos: 15,
    grasas: 0.5,
    porcion: "100 g",
  },
  {
    nombre: "Kiwi sin cáscara",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 61,
    proteinas: 1.1,
    carbohidratos: 15,
    grasas: 0.5,
    porcion: "100 g",
  },
  {
    nombre: "Kiwi verde",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 61,
    proteinas: 1.1,
    carbohidratos: 15,
    grasas: 0.5,
    porcion: "100 g",
  },
  {
    nombre: "Lima",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 30,
    proteinas: 0.7,
    carbohidratos: 11,
    grasas: 0.2,
    porcion: "100 g",
  },
  {
    nombre: "Lima fresco",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 30,
    proteinas: 0.7,
    carbohidratos: 11,
    grasas: 0.2,
    porcion: "100 g",
  },
  {
    nombre: "Lima sin cáscara",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 30,
    proteinas: 0.7,
    carbohidratos: 11,
    grasas: 0.2,
    porcion: "100 g",
  },
  {
    nombre: "Lima verde",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 30,
    proteinas: 0.7,
    carbohidratos: 11,
    grasas: 0.2,
    porcion: "100 g",
  },
  {
    nombre: "Limón",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 29,
    proteinas: 1.1,
    carbohidratos: 9,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Limón andino",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 29,
    proteinas: 1.1,
    carbohidratos: 9,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Limón cortado",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 29,
    proteinas: 1.1,
    carbohidratos: 9,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Limón maduro",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 29,
    proteinas: 1.1,
    carbohidratos: 9,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Lúcuma",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 97,
    proteinas: 1.4,
    carbohidratos: 24,
    grasas: 0.2,
    porcion: "100 g",
  },
  {
    nombre: "Mandarina",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 53,
    proteinas: 0.8,
    carbohidratos: 13,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Mandarina fresco",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 53,
    proteinas: 0.8,
    carbohidratos: 13,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Mandarina sin cáscara",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 53,
    proteinas: 0.8,
    carbohidratos: 13,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Mandarina verde",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 53,
    proteinas: 0.8,
    carbohidratos: 13,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Mango",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 60,
    proteinas: 0.8,
    carbohidratos: 15,
    grasas: 0.4,
    porcion: "100 g",
  },
  {
    nombre: "Mango fresco",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 60,
    proteinas: 0.8,
    carbohidratos: 15,
    grasas: 0.4,
    porcion: "100 g",
  },
  {
    nombre: "Mango sin cáscara",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 60,
    proteinas: 0.8,
    carbohidratos: 15,
    grasas: 0.4,
    porcion: "100 g",
  },
  {
    nombre: "Mango verde",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 60,
    proteinas: 0.8,
    carbohidratos: 15,
    grasas: 0.4,
    porcion: "100 g",
  },
  {
    nombre: "Manzana",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 52,
    proteinas: 0.3,
    carbohidratos: 14,
    grasas: 0.2,
    porcion: "100 g",
  },
  {
    nombre: "Manzana andino",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 52,
    proteinas: 0.3,
    carbohidratos: 14,
    grasas: 0.2,
    porcion: "100 g",
  },
  {
    nombre: "Manzana cortado",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 52,
    proteinas: 0.3,
    carbohidratos: 14,
    grasas: 0.2,
    porcion: "100 g",
  },
  {
    nombre: "Manzana maduro",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 52,
    proteinas: 0.3,
    carbohidratos: 14,
    grasas: 0.2,
    porcion: "100 g",
  },
  {
    nombre: "Maracuyá",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 97,
    proteinas: 2.2,
    carbohidratos: 23,
    grasas: 0.7,
    porcion: "100 g",
  },
  {
    nombre: "Melón",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 34,
    proteinas: 0.8,
    carbohidratos: 8,
    grasas: 0.2,
    porcion: "100 g",
  },
  {
    nombre: "Membrillo",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 57,
    proteinas: 0.4,
    carbohidratos: 15,
    grasas: 0.1,
    porcion: "100 g",
  },
  {
    nombre: "Mora",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 43,
    proteinas: 1.4,
    carbohidratos: 10,
    grasas: 0.5,
    porcion: "100 g",
  },
  {
    nombre: "Naranja",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 47,
    proteinas: 0.9,
    carbohidratos: 12,
    grasas: 0.1,
    porcion: "100 g",
  },
  {
    nombre: "Naranja andino",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 47,
    proteinas: 0.9,
    carbohidratos: 12,
    grasas: 0.1,
    porcion: "100 g",
  },
  {
    nombre: "Naranja cortado",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 47,
    proteinas: 0.9,
    carbohidratos: 12,
    grasas: 0.1,
    porcion: "100 g",
  },
  {
    nombre: "Naranja maduro",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 47,
    proteinas: 0.9,
    carbohidratos: 12,
    grasas: 0.1,
    porcion: "100 g",
  },
  {
    nombre: "Níspero",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 47,
    proteinas: 0.4,
    carbohidratos: 12,
    grasas: 0.2,
    porcion: "100 g",
  },
  {
    nombre: "Papaya",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 43,
    proteinas: 0.5,
    carbohidratos: 11,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Papaya andino",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 43,
    proteinas: 0.5,
    carbohidratos: 11,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Papaya cortado",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 43,
    proteinas: 0.5,
    carbohidratos: 11,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Papaya maduro",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 43,
    proteinas: 0.5,
    carbohidratos: 11,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Pasa de uva",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 299,
    proteinas: 3.1,
    carbohidratos: 79,
    grasas: 0.5,
    porcion: "100 g",
  },
  {
    nombre: "Pasas",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 299,
    proteinas: 3.1,
    carbohidratos: 79,
    grasas: 0.5,
    porcion: "100 g",
  },
  {
    nombre: "Pera",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 57,
    proteinas: 0.4,
    carbohidratos: 15,
    grasas: 0.1,
    porcion: "100 g",
  },
  {
    nombre: "Pera fresco",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 57,
    proteinas: 0.4,
    carbohidratos: 15,
    grasas: 0.1,
    porcion: "100 g",
  },
  {
    nombre: "Pera sin cáscara",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 57,
    proteinas: 0.4,
    carbohidratos: 15,
    grasas: 0.1,
    porcion: "100 g",
  },
  {
    nombre: "Pera verde",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 57,
    proteinas: 0.4,
    carbohidratos: 15,
    grasas: 0.1,
    porcion: "100 g",
  },
  {
    nombre: "Piña",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 50,
    proteinas: 0.5,
    carbohidratos: 13,
    grasas: 0.1,
    porcion: "100 g",
  },
  {
    nombre: "Piña fresco",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 50,
    proteinas: 0.5,
    carbohidratos: 13,
    grasas: 0.1,
    porcion: "100 g",
  },
  {
    nombre: "Piña sin cáscara",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 50,
    proteinas: 0.5,
    carbohidratos: 13,
    grasas: 0.1,
    porcion: "100 g",
  },
  {
    nombre: "Piña verde",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 50,
    proteinas: 0.5,
    carbohidratos: 13,
    grasas: 0.1,
    porcion: "100 g",
  },
  {
    nombre: "Plátano",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 89,
    proteinas: 1.1,
    carbohidratos: 23,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Plátano fresco",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 89,
    proteinas: 1.1,
    carbohidratos: 23,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Plátano sin cáscara",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 89,
    proteinas: 1.1,
    carbohidratos: 23,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Plátano verde",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 89,
    proteinas: 1.1,
    carbohidratos: 23,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Sandía",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 30,
    proteinas: 0.6,
    carbohidratos: 8,
    grasas: 0.2,
    porcion: "100 g",
  },
  {
    nombre: "Tuna",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 41,
    proteinas: 0.7,
    carbohidratos: 10,
    grasas: 0.5,
    porcion: "100 g",
  },
  {
    nombre: "Uva",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 69,
    proteinas: 0.7,
    carbohidratos: 18,
    grasas: 0.2,
    porcion: "100 g",
  },
  {
    nombre: "Uva andino",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 69,
    proteinas: 0.7,
    carbohidratos: 18,
    grasas: 0.2,
    porcion: "100 g",
  },
  {
    nombre: "Uva cortado",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 69,
    proteinas: 0.7,
    carbohidratos: 18,
    grasas: 0.2,
    porcion: "100 g",
  },
  {
    nombre: "Uva maduro",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 69,
    proteinas: 0.7,
    carbohidratos: 18,
    grasas: 0.2,
    porcion: "100 g",
  },
  {
    nombre: "Zapote",
    categoria: "Frutos",
    categoria_enum: null,
    calorias: 124,
    proteinas: 1.5,
    carbohidratos: 32,
    grasas: 0.4,
    porcion: "100 g",
  },
];

async function main() {
  await prisma.alimento.createMany({
    data: data.map((item) => ({
      nombre: item.nombre,
      categoria: item.categoria,
      categoria_enum: item.categoria_enum ? AlimentoCategoria[item.categoria_enum] : AlimentoCategoria.Frutos,
      calorias: item.calorias,
      proteinas: item.proteinas,
      carbohidratos: item.carbohidratos,
      grasas: item.grasas,
      porcion: item.porcion,
    })),
  });

  console.log(`Insertados ${data.length} registros en 04_frutos.seed.ts`);
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
