import { AlimentoCategoria, PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

type SeedCategory = keyof typeof AlimentoCategoria | null;

type SeedFoodRecord = {
  nombre: string;
  categoria: string;
  categoria_enum: SeedCategory;
  calorias: number;
  proteinas: number;
  carbohidratos: number;
  grasas: number;
  porcion: string;
};

const data: SeedFoodRecord[] = [
  {
    nombre: "Agua",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 0,
    proteinas: 0,
    carbohidratos: 0,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Agua",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 0,
    proteinas: 0,
    carbohidratos: 0,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Agua caliente",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 0,
    proteinas: 0,
    carbohidratos: 0,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Agua con gas",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 0,
    proteinas: 0,
    carbohidratos: 0,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Agua con limón",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 2,
    proteinas: 0,
    carbohidratos: 0.5,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Agua con limón con hielo",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 2,
    proteinas: 0,
    carbohidratos: 0.5,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Agua con limón fría",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 2,
    proteinas: 0,
    carbohidratos: 0.5,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Agua con limón sin azúcar",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 2,
    proteinas: 0,
    carbohidratos: 0.5,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Agua light",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 0,
    proteinas: 0,
    carbohidratos: 0,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Agua mineral",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 0,
    proteinas: 0,
    carbohidratos: 0,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Café americano",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 2,
    proteinas: 0.1,
    carbohidratos: 0,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Café americano con hielo",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 2,
    proteinas: 0.1,
    carbohidratos: 0,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Café americano fría",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 2,
    proteinas: 0.1,
    carbohidratos: 0,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Café americano sin azúcar",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 2,
    proteinas: 0.1,
    carbohidratos: 0,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Café descafeinado",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 2,
    proteinas: 0.1,
    carbohidratos: 0,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Café descafeinado con hielo",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 2,
    proteinas: 0.1,
    carbohidratos: 0,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Café descafeinado fría",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 2,
    proteinas: 0.1,
    carbohidratos: 0,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Café descafeinado sin azúcar",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 2,
    proteinas: 0.1,
    carbohidratos: 0,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Café instantáneo",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 4,
    proteinas: 0.1,
    carbohidratos: 0.8,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Café instantáneo caliente",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 4,
    proteinas: 0.1,
    carbohidratos: 0.8,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Café instantáneo light",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 4,
    proteinas: 0.1,
    carbohidratos: 0.8,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Café instantáneo natural",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 4,
    proteinas: 0.1,
    carbohidratos: 0.8,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Café negro",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 2,
    proteinas: 0.1,
    carbohidratos: 0,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Café negro caliente",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 2,
    proteinas: 0.1,
    carbohidratos: 0,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Café negro light",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 2,
    proteinas: 0.1,
    carbohidratos: 0,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Café negro natural",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 2,
    proteinas: 0.1,
    carbohidratos: 0,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Gaseosa cero azúcar cola",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 0,
    proteinas: 0,
    carbohidratos: 0,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Gaseosa cero azúcar limón",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 0,
    proteinas: 0,
    carbohidratos: 0,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Gaseosa cero azúcar naranja",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 0,
    proteinas: 0,
    carbohidratos: 0,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Infusión de anís",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 2,
    proteinas: 0,
    carbohidratos: 0.5,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Infusión de anís con hielo",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 2,
    proteinas: 0,
    carbohidratos: 0.5,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Infusión de anís fría",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 2,
    proteinas: 0,
    carbohidratos: 0.5,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Infusión de anís sin azúcar",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 2,
    proteinas: 0,
    carbohidratos: 0.5,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Infusión de boldo",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 1,
    proteinas: 0,
    carbohidratos: 0.2,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Infusión de canela",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 2,
    proteinas: 0,
    carbohidratos: 0.5,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Infusión de canela con hielo",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 2,
    proteinas: 0,
    carbohidratos: 0.5,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Infusión de canela fría",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 2,
    proteinas: 0,
    carbohidratos: 0.5,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Infusión de canela sin azúcar",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 2,
    proteinas: 0,
    carbohidratos: 0.5,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Infusión de cedrón",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 1,
    proteinas: 0,
    carbohidratos: 0.2,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Infusión de cedrón con hielo",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 1,
    proteinas: 0,
    carbohidratos: 0.2,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Infusión de cedrón fría",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 1,
    proteinas: 0,
    carbohidratos: 0.2,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Infusión de cedrón sin azúcar",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 1,
    proteinas: 0,
    carbohidratos: 0.2,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Infusión de coca",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 1,
    proteinas: 0,
    carbohidratos: 0.2,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Infusión de coca caliente",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 1,
    proteinas: 0,
    carbohidratos: 0.2,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Infusión de coca light",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 1,
    proteinas: 0,
    carbohidratos: 0.2,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Infusión de coca natural",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 1,
    proteinas: 0,
    carbohidratos: 0.2,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Infusión de eucalipto",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 1,
    proteinas: 0,
    carbohidratos: 0.2,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Infusión de hierba luisa",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 1,
    proteinas: 0,
    carbohidratos: 0.2,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Infusión de jamaica",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 18,
    proteinas: 0,
    carbohidratos: 4.5,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Infusión de jengibre",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 2,
    proteinas: 0,
    carbohidratos: 0.5,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Infusión de manzanilla",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 1,
    proteinas: 0,
    carbohidratos: 0.2,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Infusión de manzanilla caliente",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 1,
    proteinas: 0,
    carbohidratos: 0.2,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Infusión de manzanilla light",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 1,
    proteinas: 0,
    carbohidratos: 0.2,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Infusión de manzanilla natural",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 1,
    proteinas: 0,
    carbohidratos: 0.2,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Infusión de menta",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 1,
    proteinas: 0,
    carbohidratos: 0.2,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Infusión de menta caliente",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 1,
    proteinas: 0,
    carbohidratos: 0.2,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Infusión de menta light",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 1,
    proteinas: 0,
    carbohidratos: 0.2,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Infusión de menta natural",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 1,
    proteinas: 0,
    carbohidratos: 0.2,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Infusión de romero",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 1,
    proteinas: 0,
    carbohidratos: 0.2,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Infusión de tilo",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 1,
    proteinas: 0,
    carbohidratos: 0.2,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Infusión de toronjil",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 1,
    proteinas: 0,
    carbohidratos: 0.2,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Kombucha light",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 15,
    proteinas: 0,
    carbohidratos: 4,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Limonada sin azúcar",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 4,
    proteinas: 0,
    carbohidratos: 1,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Limonada sin azúcar con hielo",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 4,
    proteinas: 0,
    carbohidratos: 1,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Limonada sin azúcar fría",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 4,
    proteinas: 0,
    carbohidratos: 1,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Limonada sin azúcar sin azúcar",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 4,
    proteinas: 0,
    carbohidratos: 1,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Mate de coca",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 1,
    proteinas: 0,
    carbohidratos: 0.2,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Mate de coca caliente",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 1,
    proteinas: 0,
    carbohidratos: 0.2,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Mate de coca light",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 1,
    proteinas: 0,
    carbohidratos: 0.2,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Mate de coca natural",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 1,
    proteinas: 0,
    carbohidratos: 0.2,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Mate de muña",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 1,
    proteinas: 0,
    carbohidratos: 0.2,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Mate de muña con hielo",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 1,
    proteinas: 0,
    carbohidratos: 0.2,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Mate de muña fría",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 1,
    proteinas: 0,
    carbohidratos: 0.2,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Mate de muña sin azúcar",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 1,
    proteinas: 0,
    carbohidratos: 0.2,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Refresco de canela",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 24,
    proteinas: 0,
    carbohidratos: 6,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Refresco de canela caliente",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 24,
    proteinas: 0,
    carbohidratos: 6,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Refresco de canela light",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 24,
    proteinas: 0,
    carbohidratos: 6,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Refresco de canela natural",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 24,
    proteinas: 0,
    carbohidratos: 6,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Refresco de cebada",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 35,
    proteinas: 0.5,
    carbohidratos: 8,
    grasas: 0.1,
    porcion: "100 ml",
  },
  {
    nombre: "Refresco de cebada con hielo",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 35,
    proteinas: 0.5,
    carbohidratos: 8,
    grasas: 0.1,
    porcion: "100 ml",
  },
  {
    nombre: "Refresco de cebada fría",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 35,
    proteinas: 0.5,
    carbohidratos: 8,
    grasas: 0.1,
    porcion: "100 ml",
  },
  {
    nombre: "Refresco de cebada sin azúcar",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 35,
    proteinas: 0.5,
    carbohidratos: 8,
    grasas: 0.1,
    porcion: "100 ml",
  },
  {
    nombre: "Refresco de linaza",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 20,
    proteinas: 0.6,
    carbohidratos: 4,
    grasas: 0.5,
    porcion: "100 ml",
  },
  {
    nombre: "Refresco de linaza caliente",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 20,
    proteinas: 0.6,
    carbohidratos: 4,
    grasas: 0.5,
    porcion: "100 ml",
  },
  {
    nombre: "Refresco de linaza light",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 20,
    proteinas: 0.6,
    carbohidratos: 4,
    grasas: 0.5,
    porcion: "100 ml",
  },
  {
    nombre: "Refresco de linaza natural",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 20,
    proteinas: 0.6,
    carbohidratos: 4,
    grasas: 0.5,
    porcion: "100 ml",
  },
  {
    nombre: "Té blanco",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 1,
    proteinas: 0,
    carbohidratos: 0.2,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Té de durazno",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 2,
    proteinas: 0,
    carbohidratos: 0.5,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Té de frutos rojos",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 2,
    proteinas: 0,
    carbohidratos: 0.5,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Té de hierbas",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 1,
    proteinas: 0,
    carbohidratos: 0.2,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Té de manzana",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 2,
    proteinas: 0,
    carbohidratos: 0.5,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Té negro",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 1,
    proteinas: 0,
    carbohidratos: 0.2,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Té negro con hielo",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 1,
    proteinas: 0,
    carbohidratos: 0.2,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Té negro fría",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 1,
    proteinas: 0,
    carbohidratos: 0.2,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Té negro sin azúcar",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 1,
    proteinas: 0,
    carbohidratos: 0.2,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Té rojo",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 1,
    proteinas: 0,
    carbohidratos: 0.2,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Té verde",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 1,
    proteinas: 0,
    carbohidratos: 0.2,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Té verde caliente",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 1,
    proteinas: 0,
    carbohidratos: 0.2,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Té verde light",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 1,
    proteinas: 0,
    carbohidratos: 0.2,
    grasas: 0,
    porcion: "100 ml",
  },
  {
    nombre: "Té verde natural",
    categoria: "BebidasInfusiones",
    categoria_enum: "BebidasInfusiones",
    calorias: 1,
    proteinas: 0,
    carbohidratos: 0.2,
    grasas: 0,
    porcion: "100 ml",
  },
];

async function main() {
  await prisma.alimento.createMany({
    data: data.map((item) => ({
      nombre: item.nombre,
      categoria: item.categoria,
      categoria_enum: item.categoria_enum ? AlimentoCategoria[item.categoria_enum] : null,
      calorias: item.calorias,
      proteinas: item.proteinas,
      carbohidratos: item.carbohidratos,
      grasas: item.grasas,
      porcion: item.porcion,
    })),
  });

  console.log(`Insertados ${data.length} registros en 05_bebidas_infusiones.seed.ts`);
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
