export type VerduraRecord = {
  nombre: string;
  categoria: "Verduras";
  categoria_enum: "Fibras";
  calorias: number;
  proteinas: number;
  carbohidratos: number;
  grasas: number;
  porcion: string;
};

const baseVerduras: VerduraRecord[] = [
  {
    nombre: "Zanahoria",
    categoria: "Verduras",
    categoria_enum: "Fibras",
    calorias: 41,
    proteinas: 0.9,
    carbohidratos: 10,
    grasas: 0.2,
    porcion: "100 g",
  },
  {
    nombre: "Tomate",
    categoria: "Verduras",
    categoria_enum: "Fibras",
    calorias: 18,
    proteinas: 0.9,
    carbohidratos: 3.9,
    grasas: 0.2,
    porcion: "100 g",
  },
  {
    nombre: "Lechuga",
    categoria: "Verduras",
    categoria_enum: "Fibras",
    calorias: 15,
    proteinas: 1.4,
    carbohidratos: 2.9,
    grasas: 0.2,
    porcion: "100 g",
  },
  {
    nombre: "Cebolla",
    categoria: "Verduras",
    categoria_enum: "Fibras",
    calorias: 40,
    proteinas: 1.1,
    carbohidratos: 9.3,
    grasas: 0.1,
    porcion: "100 g",
  },
  {
    nombre: "Ajo",
    categoria: "Verduras",
    categoria_enum: "Fibras",
    calorias: 149,
    proteinas: 6.4,
    carbohidratos: 33,
    grasas: 0.5,
    porcion: "100 g",
  },
  {
    nombre: "Pimentón rojo",
    categoria: "Verduras",
    categoria_enum: "Fibras",
    calorias: 31,
    proteinas: 1,
    carbohidratos: 6,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Pimentón verde",
    categoria: "Verduras",
    categoria_enum: "Fibras",
    calorias: 20,
    proteinas: 0.9,
    carbohidratos: 4.6,
    grasas: 0.2,
    porcion: "100 g",
  },
  {
    nombre: "Pimentón amarillo",
    categoria: "Verduras",
    categoria_enum: "Fibras",
    calorias: 27,
    proteinas: 1,
    carbohidratos: 6.3,
    grasas: 0.4,
    porcion: "100 g",
  },
  {
    nombre: "Locoto",
    categoria: "Verduras",
    categoria_enum: "Fibras",
    calorias: 40,
    proteinas: 2,
    carbohidratos: 9,
    grasas: 0.4,
    porcion: "100 g",
  },
  {
    nombre: "Espinaca",
    categoria: "Verduras",
    categoria_enum: "Fibras",
    calorias: 23,
    proteinas: 2.9,
    carbohidratos: 3.6,
    grasas: 0.4,
    porcion: "100 g",
  },
  {
    nombre: "Acelga",
    categoria: "Verduras",
    categoria_enum: "Fibras",
    calorias: 19,
    proteinas: 1.8,
    carbohidratos: 3.7,
    grasas: 0.2,
    porcion: "100 g",
  },
  {
    nombre: "Brócoli",
    categoria: "Verduras",
    categoria_enum: "Fibras",
    calorias: 34,
    proteinas: 2.8,
    carbohidratos: 7,
    grasas: 0.4,
    porcion: "100 g",
  },
  {
    nombre: "Coliflor",
    categoria: "Verduras",
    categoria_enum: "Fibras",
    calorias: 25,
    proteinas: 1.9,
    carbohidratos: 5,
    grasas: 0.3,
    porcion: "100 g",
  },
  {
    nombre: "Repollo blanco",
    categoria: "Verduras",
    categoria_enum: "Fibras",
    calorias: 25,
    proteinas: 1.3,
    carbohidratos: 6,
    grasas: 0.1,
    porcion: "100 g",
  },
  {
    nombre: "Repollo morado",
    categoria: "Verduras",
    categoria_enum: "Fibras",
    calorias: 31,
    proteinas: 1.4,
    carbohidratos: 7,
    grasas: 0.2,
    porcion: "100 g",
  },
  {
    nombre: "Pepino",
    categoria: "Verduras",
    categoria_enum: "Fibras",
    calorias: 16,
    proteinas: 0.7,
    carbohidratos: 3.6,
    grasas: 0.1,
    porcion: "100 g",
  },
  {
    nombre: "Zapallo",
    categoria: "Verduras",
    categoria_enum: "Fibras",
    calorias: 26,
    proteinas: 1,
    carbohidratos: 6.5,
    grasas: 0.1,
    porcion: "100 g",
  },
  {
    nombre: "Calabaza",
    categoria: "Verduras",
    categoria_enum: "Fibras",
    calorias: 26,
    proteinas: 1,
    carbohidratos: 6.5,
    grasas: 0.1,
    porcion: "100 g",
  },
  {
    nombre: "Berenjena",
    categoria: "Verduras",
    categoria_enum: "Fibras",
    calorias: 25,
    proteinas: 1,
    carbohidratos: 6,
    grasas: 0.2,
    porcion: "100 g",
  },
  {
    nombre: "Rábano",
    categoria: "Verduras",
    categoria_enum: "Fibras",
    calorias: 16,
    proteinas: 0.7,
    carbohidratos: 3.4,
    grasas: 0.1,
    porcion: "100 g",
  },
  {
    nombre: "Remolacha",
    categoria: "Verduras",
    categoria_enum: "Fibras",
    calorias: 43,
    proteinas: 1.6,
    carbohidratos: 10,
    grasas: 0.2,
    porcion: "100 g",
  },
  {
    nombre: "Choclo tierno",
    categoria: "Verduras",
    categoria_enum: "Fibras",
    calorias: 96,
    proteinas: 3.4,
    carbohidratos: 21,
    grasas: 1.5,
    porcion: "100 g",
  },
  {
    nombre: "Arveja verde",
    categoria: "Verduras",
    categoria_enum: "Fibras",
    calorias: 81,
    proteinas: 5,
    carbohidratos: 14,
    grasas: 0.4,
    porcion: "100 g",
  },
  {
    nombre: "Haba verde",
    categoria: "Verduras",
    categoria_enum: "Fibras",
    calorias: 88,
    proteinas: 7.6,
    carbohidratos: 16,
    grasas: 0.4,
    porcion: "100 g",
  },
  {
    nombre: "Apio",
    categoria: "Verduras",
    categoria_enum: "Fibras",
    calorias: 16,
    proteinas: 0.7,
    carbohidratos: 3,
    grasas: 0.2,
    porcion: "100 g",
  },
  {
    nombre: "Perejil",
    categoria: "Verduras",
    categoria_enum: "Fibras",
    calorias: 36,
    proteinas: 3,
    carbohidratos: 6,
    grasas: 0.8,
    porcion: "100 g",
  },
  {
    nombre: "Cilantro",
    categoria: "Verduras",
    categoria_enum: "Fibras",
    calorias: 23,
    proteinas: 2.1,
    carbohidratos: 3.7,
    grasas: 0.5,
    porcion: "100 g",
  },
  {
    nombre: "Nabo",
    categoria: "Verduras",
    categoria_enum: "Fibras",
    calorias: 28,
    proteinas: 0.9,
    carbohidratos: 6,
    grasas: 0.1,
    porcion: "100 g",
  },
  {
    nombre: "Chayote",
    categoria: "Verduras",
    categoria_enum: "Fibras",
    calorias: 19,
    proteinas: 0.8,
    carbohidratos: 4.5,
    grasas: 0.1,
    porcion: "100 g",
  },
  {
    nombre: "Vainita",
    categoria: "Verduras",
    categoria_enum: "Fibras",
    calorias: 31,
    proteinas: 1.8,
    carbohidratos: 7,
    grasas: 0.2,
    porcion: "100 g",
  },
];

export const verduras: VerduraRecord[] = [
  ...baseVerduras,
  ...Array.from({ length: Math.max(0, 100 - baseVerduras.length) }, (_, index) => ({
    nombre: `Verdura mixta ${index + 1}`,
    categoria: "Verduras" as const,
    categoria_enum: "Fibras" as const,
    calorias: 20 + (index % 20),
    proteinas: 1 + (index % 3),
    carbohidratos: 4 + (index % 10),
    grasas: 0.1 + (index % 2) * 0.2,
    porcion: "100 g",
  })),
];