export const requiredFoodCategories = [
  "carbs",
  "proteins",
  "fats",
  "vegetables",
  "fruits",
  "infusions",
] as const;

export type FoodCategoryKey = (typeof requiredFoodCategories)[number];

export type FoodCategoryMeta = {
  label: string;
  description: string;
  searchPlaceholder: string;
  emptyState: string;
  foods: string[];
};

export const foodCatalog: Record<FoodCategoryKey, FoodCategoryMeta> = {
  carbs: {
    label: "Carbohidratos",
    description: "Bases de energia para tus comidas principales y meriendas.",
    searchPlaceholder: "Busca arroz, papa, avena o quinua",
    emptyState: "No encontramos carbohidratos con ese nombre.",
    foods: [
    "Amaranto cocido",
    "Arepa de maíz",
    "Arroz basmati cocido",
    "Arroz blanco cocido",
    "Arroz blanco cocido blanca",
    "Arroz blanco cocido gallina",
    "Arroz integral cocido",
    "Arroz integral cocido amarilla",
    "Arroz integral cocido grande",
    "Arroz jazmín cocido",
    "Arroz salvaje cocido",
    "Arveja cocida",
    "Avena cocida",
    "Avena cocida blanca",
    "Avena cocida orgánica",
    "Avena instantánea cocida",
    "Avena instantánea cocida amarilla",
    "Avena instantánea cocida hervida",
    "Azúcar",
    "Bizcocho",
    "Camote amarillo cocido",
    "Camote amarillo cocido grande",
    "Camote cocido",
    "Camote cocido gallina",
    "Camote morado cocido",
    "Camote morado cocido pequeña",
    "Camote",
    "Cebada cocida",
    "Cebada cocida morada",
    "Cereal de maíz",
    "Cereal de trigo",
    "Choclo hervido",
    "Chuño rehidratado",
    "Croissant",
    "Cuscús cocido",
    "Donut",
    "Fideo cocido",
    "Fideo cocido de campo",
    "Fideo cocido sin sal",
    "Fideo integral cocido",
    "Frijol cocido",
    "Galleta integral",
    "Galleta simple",
    "Garbanzo cocido",
    "Gelatina preparada",
    "Granola",
    "Haba cocida",
    "Harina de arroz",
    "Harina de avena",
    "Harina de maíz",
    "Harina de quinua",
    "Harina de trigo",
    "Harina de yuca",
    "Lenteja cocida",
    "Maíz inflado",
    "Maíz tostado",
    "Mermelada",
    "Miel",
    "Mote de maíz cocido",
    "Mote de maíz cocido corte rodaja",
    "Pan blanco",
    "Pan de centeno",
    "Pan de molde",
    "Pan dulce",
    "Pan integral",
    "Pan multicereal",
    "Pan pita",
    "Papa amarilla cocida",
    "Papa blanca cocida",
    "Papa blanca cocida hervida",
    "Papa cocida",
    "Papa cocida orgánica",
    "Papa morada cocida",
    "Papa morada cocida sin sal",
    "Papa roja cocida",
    "Papa roja cocida al vapor",
    "Oca cocida",
    "Pasta de arroz cocida",
    "Pasta de huevo cocida",
    "Pasta integral cocida",
    "Queque",
    "Quinua cocida",
    "Quinua cocida morada",
    "Quinua cocida pequeña",
    "Quinua negra cocida",
    "Quinua negra cocida corte rodaja",
    "Quinua negra cocida de campo",
    "Quinua roja cocida",
    "Quinua roja cocida andina",
    "Quinua roja cocida corte cubo",
    "Rosca",
    "Sorgo cocido",
    "Tortilla de maíz",
    "Tortilla de trigo",
    "Trigo cocido",
    "Trigo cocido al vapor",
    "Trigo cocido andina",
    "Tunta rehidratada",
    "Yuca cocida",
    "Yuca cocida corte cubo",
    ],
  },
  proteins: {
    label: "Proteinas",
    description: "Fuentes de saciedad y soporte muscular para tu plan.",
    searchPlaceholder: "Busca pollo, huevo, atun o yogurt",
    emptyState: "No encontramos proteinas con ese nombre.",
    foods: [
    "Arveja cocida",
    "Atún en agua",
    "Atún en agua desmenuzado",
    "Atún en agua natural",
    "Atún en agua sin piel",
    "Camarón cocido",
    "Carne de alpaca cocida",
    "Carne de cerdo magra cocida",
    "Carne de cerdo magra cocida a la plancha",
    "Carne de cerdo magra cocida magra",
    "Carne de cerdo magra cocida sin grasa",
    "Carne de llama cocida",
    "Carne de res magra cocida",
    "Carne de res magra cocida desmenuzado",
    "Carne de res magra cocida natural",
    "Carne de res magra cocida sin piel",
    "Carne molida magra cocida",
    "Charque desgrasado",
    "Corazón de res cocido",
    "Filete de pollo cocido",
    "Frijol cocido",
    "Garbanzo cocido",
    "Haba cocida",
    "Hígado de res cocido",
    "Huevo cocido",
    "Huevo cocido firme",
    "Huevo cocido hervido",
    "Huevo revuelto",
    "Huevo revuelto desmenuzado",
    "Huevo revuelto natural",
    "Huevo revuelto sin piel",
    "Jurel cocido",
    "Jurel cocido desmenuzado",
    "Jurel cocido natural",
    "Jurel cocido sin piel",
    "Kéfir",
    "Leche descremada",
    "Leche descremada desmenuzado",
    "Leche descremada natural",
    "Leche descremada sin piel",
    "Leche entera",
    "Leche entera a la plancha",
    "Leche entera magra",
    "Leche entera sin grasa",
    "Lenteja cocida",
    "Molleja de pollo cocida",
    "Muslo de pollo cocido",
    "Muslo de pollo cocido firme",
    "Muslo de pollo cocido hervido",
    "Pavo cocido",
    "Pechuga de pollo cocida",
    "Pechuga de pollo cocida a la plancha",
    "Pechuga de pollo cocida magra",
    "Pechuga de pollo cocida sin grasa",
    "Pescado blanco cocido",
    "Pescado blanco cocido firme",
    "Pescado blanco cocido hervido",
    "Pescado de río cocido",
    "Pierna de pollo cocida",
    "Pollo desmenuzado cocido",
    "Quesillo",
    "Queso fresco",
    "Queso fresco a la plancha",
    "Queso fresco magra",
    "Queso fresco sin grasa",
    "Requesón",
    "Riñón de res cocido",
    "Sardina",
    "Sardina a la plancha",
    "Sardina magra",
    "Sardina sin grasa",
    "Soya cocida",
    "Surubí cocido",
    "Tempeh",
    "Tofu firme",
    "Trucha cocida",
    "Trucha cocida cocido",
    "Trucha cocida firme",
    "Trucha cocida hervido",
    "Yogur griego natural",
    "Yogur griego natural cocido",
    "Yogur griego natural firme",
    "Yogur griego natural hervido",
    "Yogur natural",
    ],
  },
  fats: {
    label: "Grasas saludables",
    description: "Opciones para completar grasas y mejorar adherencia.",
    searchPlaceholder: "Busca palta, mani, chia o aceite",
    emptyState: "No encontramos grasas con ese nombre.",
    foods: [
    "Aceite de girasol",
    "Aceite de girasol orgánico",
    "Aceite de girasol salado",
    "Aceite de girasol tostado",
    "Aceite de maíz",
    "Aceite de maíz orgánico",
    "Aceite de maíz salado",
    "Aceite de maíz tostado",
    "Aceite de oliva",
    "Aceite de oliva crudo",
    "Aceite de oliva sin sal",
    "Aceite de soya",
    "Aceite de soya crudo",
    "Aceite de soya natural",
    "Aceite de soya sin sal",
    "Aceituna",
    "Aceituna negra",
    "Aceituna verde",
    "Aguacate",
    "Aguacate orgánico",
    "Aguacate salado",
    "Aguacate tostado",
    "Almendra",
    "Almendra orgánico",
    "Almendra salado",
    "Almendra tostado",
    "Avellana",
    "Avellana orgánico",
    "Avellana salado",
    "Avellana tostado",
    "Castaña",
    "Castaña crudo",
    "Castaña natural",
    "Castaña sin sal",
    "Coco rallado",
    "Coco rallado crudo",
    "Coco rallado natural",
    "Coco rallado sin sal",
    "Crema de almendra",
    "Crema de leche",
    "Crema de maní",
    "Grasa de res",
    "Huevo entero",
    "Leche de coco",
    "Leche de coco orgánico",
    "Leche de coco salado",
    "Leche de coco tostado",
    "Linaza",
    "Linaza crudo",
    "Linaza natural",
    "Linaza sin sal",
    "Macadamia",
    "Maní",
    "Maní crudo",
    "Maní natural",
    "Maní sin sal",
    "Manteca de cerdo",
    "Mantequilla",
    "Mantequilla crudo",
    "Mantequilla natural",
    "Mantequilla sin sal",
    "Margarina",
    "Margarina orgánico",
    "Margarina salado",
    "Margarina tostado",
    "Mayonesa",
    "Nuez",
    "Nuez crudo",
    "Nuez de Brasil",
    "Nuez natural",
    "Nuez sin sal",
    "Palta",
    "Palta crudo",
    "Palta natural",
    "Palta sin sal",
    "Pecanas",
    "Pepitas de zapallo",
    "Pepitas de zapallo orgánico",
    "Pepitas de zapallo salado",
    "Pepitas de zapallo tostado",
    "Pistachos",
    "Queso crema",
    "Queso mantecoso",
    "Semilla de amapola",
    "Semilla de calabaza",
    "Semilla de chía",
    "Semilla de chía orgánico",
    "Semilla de chía salado",
    "Semilla de chía tostado",
    "Semilla de girasol",
    "Semilla de girasol crudo",
    "Semilla de girasol natural",
    "Semilla de girasol sin sal",
    "Sésamo",
    "Sésamo orgánico",
    "Sésamo salado",
    "Sésamo tostado",
    "Tahini",
    "Yema de huevo",
    ],
  },
  vegetables: {
    label: "Verduras",
    description: "Verduras frescas para dar volumen, fibra y balance a tu plan.",
    searchPlaceholder: "Busca zanahoria, tomate, brócoli o espinaca",
    emptyState: "No encontramos verduras con ese nombre.",
    foods: [
    "Zanahoria",
    "Tomate",
    "Lechuga",
    "Cebolla",
    "Ajo",
    "Pimentón rojo",
    "Pimentón verde",
    "Pimentón amarillo",
    "Locoto",
    "Espinaca",
    "Acelga",
    "Brócoli",
    "Coliflor",
    "Repollo blanco",
    "Repollo morado",
    "Pepino",
    "Zapallo",
    "Calabaza",
    "Berenjena",
    "Rábano",
    "Remolacha",
    "Choclo tierno",
    "Arveja verde",
    "Haba verde",
    "Apio",
    "Perejil",
    "Cilantro",
    "Nabo",
    "Chayote",
    "Vainita",
    ],
  },
  fruits: {
    label: "Frutos",
    description: "Frutas para snacks, desayunos y combinaciones dulces.",
    searchPlaceholder: "Busca manzana, banana, papaya o uva",
    emptyState: "No encontramos frutos con ese nombre.",
    foods: [
    "Acerola",
    "Arándano",
    "Arándano fresco",
    "Arándano sin cáscara",
    "Arándano verde",
    "Banana",
    "Banana andino",
    "Banana cortado",
    "Banana maduro",
    "Cereza",
    "Cereza andino",
    "Cereza cortado",
    "Cereza maduro",
    "Chirimoya",
    "Ciruela",
    "Ciruela fresco",
    "Ciruela sin cáscara",
    "Ciruela verde",
    "Coco fresco",
    "Dátil",
    "Durazno",
    "Durazno andino",
    "Durazno cortado",
    "Durazno maduro",
    "Frambuesa",
    "Frambuesa andino",
    "Frambuesa cortado",
    "Frambuesa maduro",
    "Fresa",
    "Fresa andino",
    "Fresa cortado",
    "Fresa maduro",
    "Frutilla",
    "Frutilla fresco",
    "Frutilla sin cáscara",
    "Frutilla verde",
    "Granada",
    "Guayaba",
    "Guinda",
    "Higo",
    "Higo seco",
    "Kiwi",
    "Kiwi fresco",
    "Kiwi sin cáscara",
    "Kiwi verde",
    "Lima",
    "Lima fresco",
    "Lima sin cáscara",
    "Lima verde",
    "Limón",
    "Limón andino",
    "Limón cortado",
    "Limón maduro",
    "Lúcuma",
    "Mandarina",
    "Mandarina fresco",
    "Mandarina sin cáscara",
    "Mandarina verde",
    "Mango",
    "Mango fresco",
    "Mango sin cáscara",
    "Mango verde",
    "Manzana",
    "Manzana andino",
    "Manzana cortado",
    "Manzana maduro",
    "Maracuyá",
    "Melón",
    "Membrillo",
    "Mora",
    "Naranja",
    "Naranja andino",
    "Naranja cortado",
    "Naranja maduro",
    "Níspero",
    "Papaya",
    "Papaya andino",
    "Papaya cortado",
    "Papaya maduro",
    "Pasa de uva",
    "Pasas",
    "Pera",
    "Pera fresco",
    "Pera sin cáscara",
    "Pera verde",
    "Piña",
    "Piña fresco",
    "Piña sin cáscara",
    "Piña verde",
    "Plátano",
    "Plátano fresco",
    "Plátano sin cáscara",
    "Plátano verde",
    "Sandía",
    "Tuna",
    "Uva",
    "Uva andino",
    "Uva cortado",
    "Uva maduro",
    "Zapote",
    ],
  },
  infusions: {
    label: "Te e infusiones",
    description: "Bebidas ligeras para acompanar hidratacion y saciedad.",
    searchPlaceholder: "Busca te verde, manzanilla, cedron o agua",
    emptyState: "No encontramos bebidas o infusiones con ese nombre.",
    foods: [
    "Agua",
    "Agua caliente",
    "Agua con gas",
    "Agua con limón",
    "Agua con limón con hielo",
    "Agua con limón fría",
    "Agua con limón sin azúcar",
    "Agua light",
    "Agua mineral",
    "Café americano",
    "Café americano con hielo",
    "Café americano fría",
    "Café americano sin azúcar",
    "Café descafeinado",
    "Café descafeinado con hielo",
    "Café descafeinado fría",
    "Café descafeinado sin azúcar",
    "Café instantáneo",
    "Café instantáneo caliente",
    "Café instantáneo light",
    "Café instantáneo natural",
    "Café negro",
    "Café negro caliente",
    "Café negro light",
    "Café negro natural",
    "Gaseosa cero azúcar cola",
    "Gaseosa cero azúcar limón",
    "Gaseosa cero azúcar naranja",
    "Infusión de anís",
    "Infusión de anís con hielo",
    "Infusión de anís fría",
    "Infusión de anís sin azúcar",
    "Infusión de boldo",
    "Infusión de canela",
    "Infusión de canela con hielo",
    "Infusión de canela fría",
    "Infusión de canela sin azúcar",
    "Infusión de cedrón",
    "Infusión de cedrón con hielo",
    "Infusión de cedrón fría",
    "Infusión de cedrón sin azúcar",
    "Infusión de coca",
    "Infusión de coca caliente",
    "Infusión de coca light",
    "Infusión de coca natural",
    "Infusión de eucalipto",
    "Infusión de hierba luisa",
    "Infusión de jamaica",
    "Infusión de jengibre",
    "Infusión de manzanilla",
    "Infusión de manzanilla caliente",
    "Infusión de manzanilla light",
    "Infusión de manzanilla natural",
    "Infusión de menta",
    "Infusión de menta caliente",
    "Infusión de menta light",
    "Infusión de menta natural",
    "Infusión de romero",
    "Infusión de tilo",
    "Infusión de toronjil",
    "Kombucha light",
    "Limonada sin azúcar",
    "Limonada sin azúcar con hielo",
    "Limonada sin azúcar fría",
    "Limonada sin azúcar sin azúcar",
    "Mate de coca",
    "Mate de coca caliente",
    "Mate de coca light",
    "Mate de coca natural",
    "Mate de muña",
    "Mate de muña con hielo",
    "Mate de muña fría",
    "Mate de muña sin azúcar",
    "Refresco de canela",
    "Refresco de canela caliente",
    "Refresco de canela light",
    "Refresco de canela natural",
    "Refresco de cebada",
    "Refresco de cebada con hielo",
    "Refresco de cebada fría",
    "Refresco de cebada sin azúcar",
    "Refresco de linaza",
    "Refresco de linaza caliente",
    "Refresco de linaza light",
    "Refresco de linaza natural",
    "Té blanco",
    "Té de durazno",
    "Té de frutos rojos",
    "Té de hierbas",
    "Té de manzana",
    "Té negro",
    "Té negro con hielo",
    "Té negro fría",
    "Té negro sin azúcar",
    "Té rojo",
    "Té verde",
    "Té verde caliente",
    "Té verde light",
    "Té verde natural",
    ],
  },
};

export const foodCategoryLabels: Record<FoodCategoryKey, string> = requiredFoodCategories.reduce(
  (acc, category) => {
    acc[category] = foodCatalog[category].label;
    return acc;
  },
  {} as Record<FoodCategoryKey, string>
);

export const foodDataset: Record<FoodCategoryKey, string[]> = requiredFoodCategories.reduce(
  (acc, category) => {
    acc[category] = foodCatalog[category].foods;
    return acc;
  },
  {} as Record<FoodCategoryKey, string[]>
);
